/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpExtension extends SuperVO {
	private java.lang.String classname;
	private java.lang.String i18nname;
	private java.lang.String id;
	private nc.vo.pub.lang.UFBoolean isactive;
	private java.lang.String module;
	private java.lang.String pk_extension;
	private java.lang.String point;
	private java.lang.String title;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String CLASSNAME = "classname";
	public static final String I18NNAME = "i18nname";
	public static final String ID = "id";
	public static final String ISACTIVE = "isactive";
	public static final String MODULE = "module";
	public static final String PK_EXTENSION = "pk_extension";
	public static final String POINT = "point";
	public static final String TITLE = "title";
			
	/**
	 * 属性classname的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getClassname () {
		return classname;
	}   
	/**
	 * 属性classname的Setter方法.
	 * 创建日期:
	 * @param newClassname java.lang.String
	 */
	public void setClassname (java.lang.String newClassname ) {
	 	this.classname = newClassname;
	} 	  
	/**
	 * 属性i18nname的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getI18nname () {
		return i18nname;
	}   
	/**
	 * 属性i18nname的Setter方法.
	 * 创建日期:
	 * @param newI18nname java.lang.String
	 */
	public void setI18nname (java.lang.String newI18nname ) {
	 	this.i18nname = newI18nname;
	} 	  
	/**
	 * 属性id的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getId () {
		return id;
	}   
	/**
	 * 属性id的Setter方法.
	 * 创建日期:
	 * @param newId java.lang.String
	 */
	public void setId (java.lang.String newId ) {
	 	this.id = newId;
	} 	  
	/**
	 * 属性isactive的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsactive () {
		return isactive;
	}   
	/**
	 * 属性isactive的Setter方法.
	 * 创建日期:
	 * @param newIsactive nc.vo.pub.lang.UFBoolean
	 */
	public void setIsactive (nc.vo.pub.lang.UFBoolean newIsactive ) {
	 	this.isactive = newIsactive;
	} 	  
	/**
	 * 属性module的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModule () {
		return module;
	}   
	/**
	 * 属性module的Setter方法.
	 * 创建日期:
	 * @param newModule java.lang.String
	 */
	public void setModule (java.lang.String newModule ) {
	 	this.module = newModule;
	} 	  
	/**
	 * 属性pk_extension的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_extension () {
		return pk_extension;
	}   
	/**
	 * 属性pk_extension的Setter方法.
	 * 创建日期:
	 * @param newPk_extension java.lang.String
	 */
	public void setPk_extension (java.lang.String newPk_extension ) {
	 	this.pk_extension = newPk_extension;
	} 	  
	/**
	 * 属性point的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPoint () {
		return point;
	}   
	/**
	 * 属性point的Setter方法.
	 * 创建日期:
	 * @param newPoint java.lang.String
	 */
	public void setPoint (java.lang.String newPoint ) {
	 	this.point = newPoint;
	} 	  
	/**
	 * 属性title的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle () {
		return title;
	}   
	/**
	 * 属性title的Setter方法.
	 * 创建日期:
	 * @param newTitle java.lang.String
	 */
	public void setTitle (java.lang.String newTitle ) {
	 	this.title = newTitle;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_extension";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_extension";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_extension";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpExtension() {
		super();	
	}    
} 


