/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpExtensionPoint extends SuperVO {
	private java.lang.String classname;
	private java.lang.String pk_extpoint;
	private java.lang.String point;
	private java.lang.String title;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String CLASSNAME = "classname";
	public static final String PK_EXTPOINT = "pk_extpoint";
	public static final String POINT = "point";
	public static final String TITLE = "title";
			
	/**
	 * 属性classname的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getClassname () {
		return classname;
	}   
	/**
	 * 属性classname的Setter方法.
	 * 创建日期:
	 * @param newClassname java.lang.String
	 */
	public void setClassname (java.lang.String newClassname ) {
	 	this.classname = newClassname;
	} 	  
	/**
	 * 属性pk_extpoint的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_extpoint () {
		return pk_extpoint;
	}   
	/**
	 * 属性pk_extpoint的Setter方法.
	 * 创建日期:
	 * @param newPk_extpoint java.lang.String
	 */
	public void setPk_extpoint (java.lang.String newPk_extpoint ) {
	 	this.pk_extpoint = newPk_extpoint;
	} 	  
	/**
	 * 属性point的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPoint () {
		return point;
	}   
	/**
	 * 属性point的Setter方法.
	 * 创建日期:
	 * @param newPoint java.lang.String
	 */
	public void setPoint (java.lang.String newPoint ) {
	 	this.point = newPoint;
	} 	  
	/**
	 * 属性title的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle () {
		return title;
	}   
	/**
	 * 属性title的Setter方法.
	 * 创建日期:
	 * @param newTitle java.lang.String
	 */
	public void setTitle (java.lang.String newTitle ) {
	 	this.title = newTitle;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_extpoint";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_extpoint";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_extpoint";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpExtensionPoint() {
		super();	
	}    
} 


