/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpMenuCategoryVO extends SuperVO {
	private nc.vo.pub.lang.UFBoolean activeflag;
	private java.lang.String pk_menucategory;
	private java.lang.String title;
	private java.lang.String id;
	private java.lang.String ordernum;
	private java.lang.String filterclass;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String ACTIVEFLAG = "activeflag";
	public static final String PK_MENUCATEGORY = "pk_menucategory";
	public static final String TITLE = "title";
	public static final String ID = "id";
	public static final String ORDERNUM = "ordernum";
	public static final String FILTERCLASS = "filterclass";
			
	/**
	 * 属性activeflag的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getActiveflag () {
		return activeflag;
	}   
	/**
	 * 属性activeflag的Setter方法.
	 * 创建日期:
	 * @param newActiveflag nc.vo.pub.lang.UFBoolean
	 */
	public void setActiveflag (nc.vo.pub.lang.UFBoolean newActiveflag ) {
	 	this.activeflag = newActiveflag;
	} 	  
	/**
	 * 属性pk_menucategory的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_menucategory () {
		return pk_menucategory;
	}   
	/**
	 * 属性pk_menucategory的Setter方法.
	 * 创建日期:
	 * @param newPk_menucategory java.lang.String
	 */
	public void setPk_menucategory (java.lang.String newPk_menucategory ) {
	 	this.pk_menucategory = newPk_menucategory;
	} 	  
	/**
	 * 属性title的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle () {
		return title;
	}   
	/**
	 * 属性title的Setter方法.
	 * 创建日期:
	 * @param newTitle java.lang.String
	 */
	public void setTitle (java.lang.String newTitle ) {
	 	this.title = newTitle;
	} 	  
	/**
	 * 属性id的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getId () {
		return id;
	}   
	/**
	 * 属性id的Setter方法.
	 * 创建日期:
	 * @param newId java.lang.String
	 */
	public void setId (java.lang.String newId ) {
	 	this.id = newId;
	} 	  
	/**
	 * 属性ordernum的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOrdernum () {
		return ordernum;
	}   
	/**
	 * 属性ordernum的Setter方法.
	 * 创建日期:
	 * @param newOrdernum java.lang.String
	 */
	public void setOrdernum (java.lang.String newOrdernum ) {
	 	this.ordernum = newOrdernum;
	} 	  
	/**
	 * 属性filterclass的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFilterclass () {
		return filterclass;
	}   
	/**
	 * 属性filterclass的Setter方法.
	 * 创建日期:
	 * @param newFilterclass java.lang.String
	 */
	public void setFilterclass (java.lang.String newFilterclass ) {
	 	this.filterclass = newFilterclass;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_menucategory";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_menucategory";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_menucategory";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpMenuCategoryVO() {
		super();	
	}    
} 


