/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpPwdSygVO extends SuperVO {
	private java.lang.String pk_pwdsgy;
	private java.lang.String name;
	private java.lang.String dftpwd;
	private java.lang.Integer minlen;
	private java.lang.Integer errorlen;
	private java.lang.Integer valdays;
	private java.lang.Integer valtipdays;
	private nc.vo.pub.lang.UFBoolean isforcemod;
	private java.lang.String overtimesyg;
	private java.lang.String serverclass;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_PWDSGY = "pk_pwdsgy";
	public static final String NAME = "name";
	public static final String DFTPWD = "dftpwd";
	public static final String MINLEN = "minlen";
	public static final String ERRORLEN = "errorlen";
	public static final String VALDAYS = "valdays";
	public static final String VALTIPDAYS = "valtipdays";
	public static final String ISFORCEMOD = "isforcemod";
	public static final String OVERTIMESYG = "overtimesyg";
	public static final String SERVERCLASS = "serverclass";
			
	/**
	 * 属性pk_pwdsgy的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_pwdsgy () {
		return pk_pwdsgy;
	}   
	/**
	 * 属性pk_pwdsgy的Setter方法.
	 * 创建日期:
	 * @param newPk_pwdsgy java.lang.String
	 */
	public void setPk_pwdsgy (java.lang.String newPk_pwdsgy ) {
	 	this.pk_pwdsgy = newPk_pwdsgy;
	} 	  
	/**
	 * 属性name的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性dftpwd的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDftpwd () {
		return dftpwd;
	}   
	/**
	 * 属性dftpwd的Setter方法.
	 * 创建日期:
	 * @param newDftpwd java.lang.String
	 */
	public void setDftpwd (java.lang.String newDftpwd ) {
	 	this.dftpwd = newDftpwd;
	} 	  
	/**
	 * 属性minlen的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getMinlen () {
		return minlen;
	}   
	/**
	 * 属性minlen的Setter方法.
	 * 创建日期:
	 * @param newMinlen java.lang.Integer
	 */
	public void setMinlen (java.lang.Integer newMinlen ) {
	 	this.minlen = newMinlen;
	} 	  
	/**
	 * 属性errorlen的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getErrorlen () {
		return errorlen;
	}   
	/**
	 * 属性errorlen的Setter方法.
	 * 创建日期:
	 * @param newErrorlen java.lang.Integer
	 */
	public void setErrorlen (java.lang.Integer newErrorlen ) {
	 	this.errorlen = newErrorlen;
	} 	  
	/**
	 * 属性valdays的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getValdays () {
		return valdays;
	}   
	/**
	 * 属性valdays的Setter方法.
	 * 创建日期:
	 * @param newValdays java.lang.Integer
	 */
	public void setValdays (java.lang.Integer newValdays ) {
	 	this.valdays = newValdays;
	} 	  
	/**
	 * 属性valtipdays的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getValtipdays () {
		return valtipdays;
	}   
	/**
	 * 属性valtipdays的Setter方法.
	 * 创建日期:
	 * @param newValtipdays java.lang.Integer
	 */
	public void setValtipdays (java.lang.Integer newValtipdays ) {
	 	this.valtipdays = newValtipdays;
	} 	  
	/**
	 * 属性isforcemod的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsforcemod () {
		return isforcemod;
	}   
	/**
	 * 属性isforcemod的Setter方法.
	 * 创建日期:
	 * @param newIsforcemod nc.vo.pub.lang.UFBoolean
	 */
	public void setIsforcemod (nc.vo.pub.lang.UFBoolean newIsforcemod ) {
	 	this.isforcemod = newIsforcemod;
	} 	  
	/**
	 * 属性overtimesyg的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOvertimesyg () {
		return overtimesyg;
	}   
	/**
	 * 属性overtimesyg的Setter方法.
	 * 创建日期:
	 * @param newOvertimesyg java.lang.String
	 */
	public void setOvertimesyg (java.lang.String newOvertimesyg ) {
	 	this.overtimesyg = newOvertimesyg;
	} 	  
	/**
	 * 属性serverclass的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getServerclass () {
		return serverclass;
	}   
	/**
	 * 属性serverclass的Setter方法.
	 * 创建日期:
	 * @param newServerclass java.lang.String
	 */
	public void setServerclass (java.lang.String newServerclass ) {
	 	this.serverclass = newServerclass;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_pwdsgy";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_pwdsyg";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_pwdsyg";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpPwdSygVO() {
		super();	
	}    
} 


