/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpRespFuncVO extends SuperVO {
	/**
	 * 职责主键
	 */
	private java.lang.String pk_responsibility;
	/**
	 * 功能资源主键
	 */
	private java.lang.String busi_pk;
	/**
	 * 功能资源名称
	 */
	private String busi_name;
	private nc.vo.pub.lang.UFDate creationtime;
	private java.lang.String creator;
	private java.lang.String dataoriginflag;
	private java.lang.String pk_group;
	/**
	 * 主键
	 */
	private java.lang.String pk_resp_func;
	private java.lang.Integer type;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_RESPONSIBILITY = "pk_responsibility";
	public static final String BUSI_PK = "busi_pk";
	public static final String CREATIONTIME = "creationtime";
	public static final String CREATOR = "creator";
	public static final String DATAORIGINFLAG = "dataoriginflag";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_RESP_FUNC = "pk_resp_func";
	public static final String TYPE = "type";
			
	/**
	 * 属性pk_responsibility的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_responsibility () {
		return pk_responsibility;
	}   
	/**
	 * 属性pk_responsibility的Setter方法.
	 * 创建日期:
	 * @param newPk_responsibility java.lang.String
	 */
	public void setPk_responsibility (java.lang.String newPk_responsibility ) {
	 	this.pk_responsibility = newPk_responsibility;
	} 	  
	/**
	 * 属性busi_pk的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_pk () {
		return busi_pk;
	}   
	/**
	 * 属性busi_pk的Setter方法.
	 * 创建日期:
	 * @param newBusi_pk java.lang.String
	 */
	public void setBusi_pk (java.lang.String newBusi_pk ) {
	 	this.busi_pk = newBusi_pk;
	} 	  
	/**
	 * 属性creationtime的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDate
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDate newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性creator的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性dataoriginflag的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDataoriginflag () {
		return dataoriginflag;
	}   
	/**
	 * 属性dataoriginflag的Setter方法.
	 * 创建日期:
	 * @param newDataoriginflag java.lang.String
	 */
	public void setDataoriginflag (java.lang.String newDataoriginflag ) {
	 	this.dataoriginflag = newDataoriginflag;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_resp_func的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_resp_func () {
		return pk_resp_func;
	}   
	/**
	 * 属性pk_resp_func的Setter方法.
	 * 创建日期:
	 * @param newPk_resp_func java.lang.String
	 */
	public void setPk_resp_func (java.lang.String newPk_resp_func ) {
	 	this.pk_resp_func = newPk_resp_func;
	} 	  
	/**
	 * 属性type的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.
	 * 创建日期:
	 * @param newType java.lang.Integer
	 */
	public void setType (java.lang.Integer newType ) {
	 	this.type = newType;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_responsibility";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_resp_func";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_resp_func";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_resp_func";
	}    
    
    public String getBusi_name() {
		return busi_name;
	}
	public void setBusi_name(String busi_name) {
		this.busi_name = busi_name;
	}
	/**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpRespFuncVO() {
		super();	
	}    
} 


