/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpResponsibilityVO extends SuperVO {
	private java.lang.String code;
	private nc.vo.pub.lang.UFDate creationtime;
	private java.lang.String creator;
	private java.lang.String dataoriginflag;
	private java.lang.String descipt;
	private nc.vo.pub.lang.UFDate modifiedtime;
	private java.lang.String modifier;
	private java.lang.String name;
	private java.lang.String name2;
	private java.lang.String name3;
	private java.lang.String name4;
	private java.lang.String name5;
	private java.lang.String name6;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String pk_responsibility;
	private java.lang.String type;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;
	
	//管理类型
	public final static Integer TYPE_ADMIN = ManageTypeVO.ADMIN_TYPE_VALUE;
	//业务类型
	public final static Integer TYPE_BUSINESS = ManageTypeVO.BUSINESS_TYPE_VALUE;

	public static final String CODE = "code";
	public static final String CREATIONTIME = "creationtime";
	public static final String CREATOR = "creator";
	public static final String DATAORIGINFLAG = "dataoriginflag";
	public static final String DESCIPT = "descipt";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String MODIFIER = "modifier";
	public static final String NAME = "name";
	public static final String NAME2 = "name2";
	public static final String NAME3 = "name3";
	public static final String NAME4 = "name4";
	public static final String NAME5 = "name5";
	public static final String NAME6 = "name6";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_RESPONSIBILITY = "pk_responsibility";
	public static final String TYPE = "type";
			
	/**
	 * 属性code的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性creationtime的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDate
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDate newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性creator的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性dataoriginflag的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDataoriginflag () {
		return dataoriginflag;
	}   
	/**
	 * 属性dataoriginflag的Setter方法.
	 * 创建日期:
	 * @param newDataoriginflag java.lang.String
	 */
	public void setDataoriginflag (java.lang.String newDataoriginflag ) {
	 	this.dataoriginflag = newDataoriginflag;
	} 	  
	/**
	 * 属性descipt的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDescipt () {
		return descipt;
	}   
	/**
	 * 属性descipt的Setter方法.
	 * 创建日期:
	 * @param newDescipt java.lang.String
	 */
	public void setDescipt (java.lang.String newDescipt ) {
	 	this.descipt = newDescipt;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDate
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDate newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性name的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性name2的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName2 () {
		return name2;
	}   
	/**
	 * 属性name2的Setter方法.
	 * 创建日期:
	 * @param newName2 java.lang.String
	 */
	public void setName2 (java.lang.String newName2 ) {
	 	this.name2 = newName2;
	} 	  
	/**
	 * 属性name3的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName3 () {
		return name3;
	}   
	/**
	 * 属性name3的Setter方法.
	 * 创建日期:
	 * @param newName3 java.lang.String
	 */
	public void setName3 (java.lang.String newName3 ) {
	 	this.name3 = newName3;
	} 	  
	/**
	 * 属性name4的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName4 () {
		return name4;
	}   
	/**
	 * 属性name4的Setter方法.
	 * 创建日期:
	 * @param newName4 java.lang.String
	 */
	public void setName4 (java.lang.String newName4 ) {
	 	this.name4 = newName4;
	} 	  
	/**
	 * 属性name5的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName5 () {
		return name5;
	}   
	/**
	 * 属性name5的Setter方法.
	 * 创建日期:
	 * @param newName5 java.lang.String
	 */
	public void setName5 (java.lang.String newName5 ) {
	 	this.name5 = newName5;
	} 	  
	/**
	 * 属性name6的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName6 () {
		return name6;
	}   
	/**
	 * 属性name6的Setter方法.
	 * 创建日期:
	 * @param newName6 java.lang.String
	 */
	public void setName6 (java.lang.String newName6 ) {
	 	this.name6 = newName6;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_responsibility的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_responsibility () {
		return pk_responsibility;
	}   
	/**
	 * 属性pk_responsibility的Setter方法.
	 * 创建日期:
	 * @param newPk_responsibility java.lang.String
	 */
	public void setPk_responsibility (java.lang.String newPk_responsibility ) {
	 	this.pk_responsibility = newPk_responsibility;
	} 	  
	/**
	 * 属性type的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.
	 * 创建日期:
	 * @param newType java.lang.String
	 */
	public void setType (java.lang.String newType ) {
	 	this.type = newType;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_responsibility";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_responsibility";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_responsibility";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpResponsibilityVO() {
		super();	
	}    
} 


