/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
import nc.vo.pub.SuperVO;
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial") public class CpResourceVO extends SuperVO {
	private java.lang.String pk_resource;
	private java.lang.String pk_group;
	private nc.vo.pub.lang.UFBoolean shareflag;
	private nc.vo.pub.lang.UFBoolean iscontrol;
	private java.lang.String resourcename;
	private java.lang.Integer resourcetype;
	private java.lang.String originalid;
	private java.lang.String operator;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;
	public static final String PK_RESOURCE = "pk_resource";
	public static final String PK_GROUP = "pk_group";
	public static final String SHAREFLAG = "shareflag";
	public static final String ISCONTROL = "iscontrol";
	public static final String RESOURCENAME = "resourcename";
	public static final String RESOURCETYPE = "resourcetype";
	public static final String ORIGINALID = "originalid";
	public static final String OPERATOR = "operator";
	public static final Integer RESOURCE_TYPE_PAGE = new Integer(1);
	public static final Integer RESOURCE_TYPE_PORTLET = new Integer(2);
	public static final Integer RESOURCE_TYPE_FUNC = new Integer(3);
	public static final Integer RESOURCE_TYPE_NEWSGROUP = new Integer(4);
	public static final Integer RESOURCE_TYPE_COMPDOCLABAL = new Integer(5);
	/**
	 * 属性pk_resource的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_resource() {
		return pk_resource;
	}
	/**
	 * 属性pk_resource的Setter方法. 创建日期:
	 * 
	 * @param newPk_resource
	 *            java.lang.String
	 */
	public void setPk_resource(java.lang.String newPk_resource) {
		this.pk_resource = newPk_resource;
	}
	/**
	 * 属性pk_group的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return pk_group;
	}
	/**
	 * 属性pk_group的Setter方法. 创建日期:
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.pk_group = newPk_group;
	}
	/**
	 * 属性shareflag的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getShareflag() {
		return shareflag;
	}
	/**
	 * 属性shareflag的Setter方法. 创建日期:
	 * 
	 * @param newShareflag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setShareflag(nc.vo.pub.lang.UFBoolean newShareflag) {
		this.shareflag = newShareflag;
	}
	/**
	 * 属性iscontrol的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIscontrol() {
		return iscontrol;
	}
	/**
	 * 属性iscontrol的Setter方法. 创建日期:
	 * 
	 * @param newIscontrol
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setIscontrol(nc.vo.pub.lang.UFBoolean newIscontrol) {
		this.iscontrol = newIscontrol;
	}
	/**
	 * 属性resourcename的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getResourcename() {
		return resourcename;
	}
	/**
	 * 属性resourcename的Setter方法. 创建日期:
	 * 
	 * @param newResourcename
	 *            java.lang.String
	 */
	public void setResourcename(java.lang.String newResourcename) {
		this.resourcename = newResourcename;
	}
	/**
	 * 属性resourcetype的Getter方法. 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getResourcetype() {
		return resourcetype;
	}
	/**
	 * 属性resourcetype的Setter方法. 创建日期:
	 * 
	 * @param newResourcetype
	 *            java.lang.Integer
	 */
	public void setResourcetype(java.lang.Integer newResourcetype) {
		this.resourcetype = newResourcetype;
	}
	/**
	 * 属性originalid的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getOriginalid() {
		return originalid;
	}
	/**
	 * 属性originalid的Setter方法. 创建日期:
	 * 
	 * @param newOriginalid
	 *            java.lang.String
	 */
	public void setOriginalid(java.lang.String newOriginalid) {
		this.originalid = newOriginalid;
	}
	/**
	 * 属性operator的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getOperator() {
		return operator;
	}
	/**
	 * 属性operator的Setter方法. 创建日期:
	 * 
	 * @param newOperator
	 *            java.lang.String
	 */
	public void setOperator(java.lang.String newOperator) {
		this.operator = newOperator;
	}
	/**
	 * 属性dr的Getter方法. 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}
	/**
	 * 属性dr的Setter方法. 创建日期:
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}
	/**
	 * 属性ts的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}
	/**
	 * 属性ts的Setter方法. 创建日期:
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}
	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}
	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_resource";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_resource";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_resource";
	}
	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:
	 */
	public CpResourceVO() {
		super();
	}
}
