/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpRoleVO extends SuperVO {
	public final static Integer ROLETYPE_ADMIN = ManageTypeVO.ADMIN_TYPE_VALUE;
	public final static Integer ROLETYPE_BUSINESS = ManageTypeVO.BUSINESS_TYPE_VALUE;
	//默认角色编码
	public final static String DEFAULT_ROLECODE = "everyone";
	//默认角色名称
	public final static String DEFAULT_ROLENAME = "默认角色";
	private java.lang.String pk_role;
	private java.lang.String rolename;
	private java.lang.String rolecode;
	private java.lang.String comments;
	private java.lang.String issealed;
	private nc.vo.pub.lang.UFDate datecreated;
	private java.lang.String usercreated;
	private java.lang.String pk_rolegroup;
	private java.lang.String pk_org;
	private java.lang.Integer type;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_ROLE = "pk_role";
	public static final String ROLENAME = "rolename";
	public static final String ROLECODE = "rolecode";
	public static final String COMMENTS = "comments";
	public static final String ISSEALED = "issealed";
	public static final String TYPE = "type";
	public static final String DATECREATED = "datecreated";
	public static final String USERCREATED = "usercreated";
	public static final String PK_ROLEGROUP = "pk_rolegroup";
			
	/**
	 * 属性pk_role的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_role () {
		return pk_role;
	}   
	/**
	 * 属性pk_role的Setter方法.
	 * 创建日期:
	 * @param newPk_role java.lang.String
	 */
	public void setPk_role (java.lang.String newPk_role ) {
	 	this.pk_role = newPk_role;
	} 	  
	/**
	 * 属性rolename的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRolename () {
		return rolename;
	}   
	/**
	 * 属性rolename的Setter方法.
	 * 创建日期:
	 * @param newRolename java.lang.String
	 */
	public void setRolename (java.lang.String newRolename ) {
	 	this.rolename = newRolename;
	} 	  
	
	public java.lang.String getPk_org() {
		return pk_org;
	}
	public void setPk_org(java.lang.String pk_org) {
		this.pk_org = pk_org;
	}
	/**
	 * 属性rolecode的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRolecode () {
		return rolecode;
	}   
	/**
	 * 属性rolecode的Setter方法.
	 * 创建日期:
	 * @param newRolecode java.lang.String
	 */
	public void setRolecode (java.lang.String newRolecode ) {
	 	this.rolecode = newRolecode;
	} 	  
	/**
	 * 属性comments的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getComments () {
		return comments;
	}   
	/**
	 * 属性comments的Setter方法.
	 * 创建日期:
	 * @param newComments java.lang.String
	 */
	public void setComments (java.lang.String newComments ) {
	 	this.comments = newComments;
	} 	  
	/**
	 * 属性issealed的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getIssealed () {
		return issealed;
	}   
	/**
	 * 属性issealed的Setter方法.
	 * 创建日期:
	 * @param newIssealed java.lang.String
	 */
	public void setIssealed (java.lang.String newIssealed ) {
	 	this.issealed = newIssealed;
	} 	  
	/**
	 * 属性datecreated的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getDatecreated () {
		return datecreated;
	}   
	/**
	 * 属性datecreated的Setter方法.
	 * 创建日期:
	 * @param newDatecreated nc.vo.pub.lang.UFDate
	 */
	public void setDatecreated (nc.vo.pub.lang.UFDate newDatecreated ) {
	 	this.datecreated = newDatecreated;
	} 	  
	/**
	 * 属性usercreated的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUsercreated () {
		return usercreated;
	}   
	/**
	 * 属性usercreated的Setter方法.
	 * 创建日期:
	 * @param newUsercreated java.lang.String
	 */
	public void setUsercreated (java.lang.String newUsercreated ) {
	 	this.usercreated = newUsercreated;
	} 	  
	/**
	 * 属性pk_rolegroup的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_rolegroup () {
		return pk_rolegroup;
	}   
	/**
	 * 属性type的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.
	 * 创建日期:
	 * @param newType java.lang.Integer
	 */
	public void setType (java.lang.Integer newType ) {
	 	this.type = newType;
	} 	
	/**
	 * 属性pk_rolegroup的Setter方法.
	 * 创建日期:
	 * @param newPk_rolegroup java.lang.String
	 */
	public void setPk_rolegroup (java.lang.String newPk_rolegroup ) {
	 	this.pk_rolegroup = newPk_rolegroup;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_role";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_role";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_role";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpRoleVO() {
		super();	
	}    
} 


