/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpRoleGroupVO extends SuperVO {
	public final static Integer ROLEGROUPTYPE_ADMIN = 0;
	public final static Integer ROLEGROUPTYPE_BUSINESS = 1;
	//默认角色组编码
	public final static String DEFAULT_ROLECODE = "everyone";
	//默认角色组名称
	public final static String DEFAULT_ROLENAME = "默认角色组";
	private java.lang.String pk_rolegroup;
	private java.lang.String groupname;
	private java.lang.String groupcode;
	private java.lang.String usercreated;
	private java.lang.Integer type;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private nc.vo.pub.lang.UFDate datecreated;
	private java.lang.String pk_parent;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_ROLEGROUP = "pk_rolegroup";
	public static final String GROUPNAME = "groupname";
	public static final String GROUPCODE = "groupcode";
	public static final String USERCREATED = "usercreated";
	public static final String TYPE = "type";
	public static final String PK_ORG = "pk_org";
	public static final String DATECREATED = "datecreated";
	public static final String PK_PARENT = "pk_parent";
			
	/**
	 * 属性pk_rolegroup的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_rolegroup () {
		return pk_rolegroup;
	}   
	/**
	 * 属性pk_rolegroup的Setter方法.
	 * 创建日期:
	 * @param newPk_rolegroup java.lang.String
	 */
	public void setPk_rolegroup (java.lang.String newPk_rolegroup ) {
	 	this.pk_rolegroup = newPk_rolegroup;
	} 	  
	/**
	 * 属性groupname的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getGroupname () {
		return groupname;
	}   
	/**
	 * 属性groupname的Setter方法.
	 * 创建日期:
	 * @param newGroupname java.lang.String
	 */
	public void setGroupname (java.lang.String newGroupname ) {
	 	this.groupname = newGroupname;
	} 	  
	/**
	 * 属性groupcode的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getGroupcode () {
		return groupcode;
	}   
	/**
	 * 属性groupcode的Setter方法.
	 * 创建日期:
	 * @param newGroupcode java.lang.String
	 */
	public void setGroupcode (java.lang.String newGroupcode ) {
	 	this.groupcode = newGroupcode;
	} 	  
	/**
	 * 属性usercreated的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUsercreated () {
		return usercreated;
	}   
	/**
	 * 属性usercreated的Setter方法.
	 * 创建日期:
	 * @param newUsercreated java.lang.String
	 */
	public void setUsercreated (java.lang.String newUsercreated ) {
	 	this.usercreated = newUsercreated;
	} 	  
	/**
	 * 属性type的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.
	 * 创建日期:
	 * @param newType java.lang.Integer
	 */
	public void setType (java.lang.Integer newType ) {
	 	this.type = newType;
	} 	  
	/**
	 * 属性pk_org的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	
	
	public java.lang.String getPk_group() {
		return pk_group;
	}
	public void setPk_group(java.lang.String pk_group) {
		this.pk_group = pk_group;
	}
	/**
	 * 属性datecreated的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getDatecreated () {
		return datecreated;
	}   
	/**
	 * 属性datecreated的Setter方法.
	 * 创建日期:
	 * @param newDatecreated nc.vo.pub.lang.UFDate
	 */
	public void setDatecreated (nc.vo.pub.lang.UFDate newDatecreated ) {
	 	this.datecreated = newDatecreated;
	} 	  
	/**
	 * 属性pk_parent的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_parent () {
		return pk_parent;
	}   
	/**
	 * 属性pk_parent的Setter方法.
	 * 创建日期:
	 * @param newPk_parent java.lang.String
	 */
	public void setPk_parent (java.lang.String newPk_parent ) {
	 	this.pk_parent = newPk_parent;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_rolegroup";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_rolegroup";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_rolegroup";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpRoleGroupVO() {
		super();	
	}    
} 


