/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpSysinitVO extends SuperVO {
	private java.lang.String pk_sysinit;
	private java.lang.String sysinit;
	private java.lang.String value;
	private java.lang.String pk_org;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String initname;
	private java.lang.String initcode;
	private nc.vo.pub.lang.UFBoolean editflag;
	private nc.vo.pub.lang.UFBoolean controlflag;
	private java.lang.Integer dataoriginflag;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	
	private java.lang.String valuelist;
	private java.lang.String remark;
	private java.lang.String defaultvalue;
	public static final String VALUELIST = "valuelist";
	public static final String REMARK = "remark";
	public static final String DEFAULTVALUE = "defaultvalue";
	                           
	public static final String PK_SYSINIT = "pk_sysinit";
	public static final String SYSINIT = "sysinit";
	public static final String VALUE = "value";
	public static final String PK_ORG = "pk_org";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String INITNAME = "initname";
	public static final String INITCODE = "initcode";
	public static final String EDITFLAG = "editflag";
	public static final String CONTROLFLAG = "controlflag";
	public static final String DATAORIGINFLAG = "dataoriginflag";
	
	
	public java.lang.String getValuelist() {
		return valuelist;
	}
	public void setValuelist(java.lang.String valuelist) {
		this.valuelist = valuelist;
	}
	public java.lang.String getRemark() {
		return remark;
	}
	public void setRemark(java.lang.String remark) {
		this.remark = remark;
	}
	public java.lang.String getDefaultvalue() {
		return defaultvalue;
	}
	public void setDefaultvalue(java.lang.String defaultvalue) {
		this.defaultvalue = defaultvalue;
	}
	
	/**
	 * 属性pk_sysinit的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_sysinit () {
		return pk_sysinit;
	}   
	/**
	 * 属性pk_sysinit的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_sysinit java.lang.String
	 */
	public void setPk_sysinit (java.lang.String newPk_sysinit ) {
	 	this.pk_sysinit = newPk_sysinit;
	} 	  
	/**
	 * 属性sysinit的Getter方法.属性名：关联模板
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSysinit () {
		return sysinit;
	}   
	/**
	 * 属性sysinit的Setter方法.属性名：关联模板
	 * 创建日期:
	 * @param newSysinit java.lang.String
	 */
	public void setSysinit (java.lang.String newSysinit ) {
	 	this.sysinit = newSysinit;
	} 	  
	/**
	 * 属性value的Getter方法.属性名：参数值
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getValue () {
		return value;
	}   
	/**
	 * 属性value的Setter方法.属性名：参数值
	 * 创建日期:
	 * @param newValue java.lang.String
	 */
	public void setValue (java.lang.String newValue ) {
	 	this.value = newValue;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织主键
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性initname的Getter方法.属性名：参数名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getInitname () {
		return initname;
	}   
	/**
	 * 属性initname的Setter方法.属性名：参数名称
	 * 创建日期:
	 * @param newInitname java.lang.String
	 */
	public void setInitname (java.lang.String newInitname ) {
	 	this.initname = newInitname;
	} 	  
	/**
	 * 属性initcode的Getter方法.属性名：参数编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getInitcode () {
		return initcode;
	}   
	/**
	 * 属性initcode的Setter方法.属性名：参数编码
	 * 创建日期:
	 * @param newInitcode java.lang.String
	 */
	public void setInitcode (java.lang.String newInitcode ) {
	 	this.initcode = newInitcode;
	} 	  
	/**
	 * 属性editflag的Getter方法.属性名：是否可编辑
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getEditflag () {
		return editflag;
	}   
	/**
	 * 属性editflag的Setter方法.属性名：是否可编辑
	 * 创建日期:
	 * @param newEditflag nc.vo.pub.lang.UFBoolean
	 */
	public void setEditflag (nc.vo.pub.lang.UFBoolean newEditflag ) {
	 	this.editflag = newEditflag;
	} 	  
	/**
	 * 属性controlflag的Getter方法.属性名：是否控制下级
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getControlflag () {
		return controlflag;
	}   
	/**
	 * 属性controlflag的Setter方法.属性名：是否控制下级
	 * 创建日期:
	 * @param newControlflag nc.vo.pub.lang.UFBoolean
	 */
	public void setControlflag (nc.vo.pub.lang.UFBoolean newControlflag ) {
	 	this.controlflag = newControlflag;
	} 	  
	/**
	 * 属性dataoriginflag的Getter方法.属性名：分布式
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDataoriginflag () {
		return dataoriginflag;
	}   
	/**
	 * 属性dataoriginflag的Setter方法.属性名：分布式
	 * 创建日期:
	 * @param newDataoriginflag java.lang.Integer
	 */
	public void setDataoriginflag (java.lang.Integer newDataoriginflag ) {
	 	this.dataoriginflag = newDataoriginflag;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_sysinit";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_sysinit";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_sysinit";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpSysinitVO() {
		super();	
	}    
} 


