/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
public class CpUserVO extends SuperVO {
	private static final long serialVersionUID = -2849291178574896036L;
	/** 身份认证方式 - 静态密码。 */
	public static final Integer AUTHENMODE_STATICPWD = Integer.valueOf(0);
	/** 身份认证方式 - 动态密码。 */
	public static final Integer AUTHENMODE_DYNAMICPWD = Integer.valueOf(1);
	/** 身份认证方式 - CA。 */
	public static final Integer AUTHENMODE_CAAUTHEN = Integer.valueOf(2);
	
	/**
	 * 集团管理员
	 *
	 */
	public static final int USER_TYPE_GROUP_ADM = 0;
	
	/**
	 * 普通用户
	 */
	public static final int USER_TYPE_USER = 1;

	/**
	 * 业务管理员
	 */
	public static final int USER_TYPE_BUSICNETER_ADM=2;//
	/**
	 * 超级管理员
	 */
	public static final int USER_TYPE_SUPER_ADM = 3;//
	
	private java.lang.String cuserid;
	private java.lang.String ncpk;	
	private java.lang.String original;
	private java.lang.String user_name;
	private java.lang.String user_name2;
	private java.lang.String user_name3;
	private java.lang.String user_name4;
	private java.lang.String user_name5;
	private java.lang.String user_name6;
	private java.lang.String user_code;
	private java.lang.String user_password;
	private java.lang.String user_note;
	private java.lang.String pwdlevelcode;
	private java.lang.String pwdparam;
	private java.lang.String identityverifycode;
	private nc.vo.pub.lang.UFDate abledate;
	private nc.vo.pub.lang.UFDate disabledate;
	private nc.vo.pub.lang.UFBoolean islocked;
	private java.lang.String pk_base_doc;
	private java.lang.Integer base_doc_type;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.Integer user_type;
	private java.lang.String pk_usergroupforcreate;
	private java.lang.String format;
	private nc.vo.pub.lang.UFBoolean isca;
	private java.lang.Integer enablestate;
	private java.lang.String contentlang;
	private java.lang.String user_code_q;
	private java.lang.Integer dataoriginflag;
	private UFBoolean isasyntonc;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;
	private java.lang.Integer passwordtrytimes ;
	public static final String CUSERID = "cuserid";
	public static final String USER_NAME = "user_name";
	public static final String USER_NAME2 = "user_name2";
	public static final String USER_NAME3 = "user_name3";
	public static final String USER_NAME4 = "user_name4";
	public static final String USER_NAME5 = "user_name5";
	public static final String USER_NAME6 = "user_name6";
	public static final String USER_CODE = "user_code";
	public static final String USER_PASSWORD = "user_password";
	public static final String USER_NOTE = "user_note";
	public static final String PWDLEVELCODE = "pwdlevelcode";
	public static final String PWDPARAM = "pwdparam";
	public static final String IDENTITYVERIFYCODE = "identityverifycode";
	public static final String ABLEDATE = "abledate";
	public static final String DISABLEDATE = "disabledate";
	public static final String ISLOCKED = "islocked";
	public static final String PK_BASE_DOC = "pk_base_doc";
	public static final String BASE_DOC_TYPE = "base_doc_type";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String USER_TYPE = "user_type";
	public static final String PK_USERGROUPFORCREATE = "pk_usergroupforcreate";
	public static final String FORMAT = "format";
	public static final String ISCA = "isca";
	public static final String ENABLESTATE = "enablestate";
	public static final String CONTENTLANG = "contentlang";
	public static final String USER_CODE_Q = "user_code_q";
	public static final String DATAORIGINFLAG = "dataoriginflag";
	public static final String PASSWORDTRYTIMES = "passwordtrytimes";
	public static final String ISNOTASYNTONC = "isasyntonc";
	public java.lang.Integer getPasswordtrytimes() {
		return passwordtrytimes;
	}
	public void setPasswordtrytimes(java.lang.Integer passwordtrytimes) {
		this.passwordtrytimes = passwordtrytimes;
	}
	/**
	 * 属性cuserid的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCuserid() {
		return cuserid;
	}
	/**
	 * 属性cuserid的Setter方法. 创建日期:
	 * 
	 * @param newCuserid
	 *            java.lang.String
	 */
	public void setCuserid(java.lang.String newCuserid) {
		this.cuserid = newCuserid;
	}
	
	public java.lang.String getNcpk() {
		return ncpk;
	}
	public void setNcpk(java.lang.String ncpk) {
		this.ncpk = ncpk;
	}
	
	public java.lang.String getOriginal() {
		return original;
	}
	public void setOriginal(java.lang.String original) {
		this.original = original;
	}
	/**
	 * 属性user_name的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_name() {
		return user_name;
	}
	/**
	 * 属性user_name的Setter方法. 创建日期:
	 * 
	 * @param newUser_name
	 *            java.lang.String
	 */
	public void setUser_name(java.lang.String newUser_name) {
		this.user_name = newUser_name;
	}
	/**
	 * 属性user_name2的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_name2() {
		return user_name2;
	}
	/**
	 * 属性user_name2的Setter方法. 创建日期:
	 * 
	 * @param newUser_name2
	 *            java.lang.String
	 */
	public void setUser_name2(java.lang.String newUser_name2) {
		this.user_name2 = newUser_name2;
	}
	/**
	 * 属性user_name3的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_name3() {
		return user_name3;
	}
	/**
	 * 属性user_name3的Setter方法. 创建日期:
	 * 
	 * @param newUser_name3
	 *            java.lang.String
	 */
	public void setUser_name3(java.lang.String newUser_name3) {
		this.user_name3 = newUser_name3;
	}
	/**
	 * 属性user_name4的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_name4() {
		return user_name4;
	}
	/**
	 * 属性user_name4的Setter方法. 创建日期:
	 * 
	 * @param newUser_name4
	 *            java.lang.String
	 */
	public void setUser_name4(java.lang.String newUser_name4) {
		this.user_name4 = newUser_name4;
	}
	/**
	 * 属性user_name5的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_name5() {
		return user_name5;
	}
	/**
	 * 属性user_name5的Setter方法. 创建日期:
	 * 
	 * @param newUser_name5
	 *            java.lang.String
	 */
	public void setUser_name5(java.lang.String newUser_name5) {
		this.user_name5 = newUser_name5;
	}
	/**
	 * 属性user_name6的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_name6() {
		return user_name6;
	}
	/**
	 * 属性user_name6的Setter方法. 创建日期:
	 * 
	 * @param newUser_name6
	 *            java.lang.String
	 */
	public void setUser_name6(java.lang.String newUser_name6) {
		this.user_name6 = newUser_name6;
	}
	/**
	 * 属性user_code的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_code() {
		return user_code;
	}
	/**
	 * 属性user_code的Setter方法. 创建日期:
	 * 
	 * @param newUser_code
	 *            java.lang.String
	 */
	public void setUser_code(java.lang.String newUser_code) {
		this.user_code = newUser_code;
	}
	/**
	 * 属性user_password的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_password() {
		return user_password;
	}
	/**
	 * 属性user_password的Setter方法. 创建日期:
	 * 
	 * @param newUser_password
	 *            java.lang.String
	 */
	public void setUser_password(java.lang.String newUser_password) {
		this.user_password = newUser_password;
	}
	/**
	 * 属性user_note的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_note() {
		return user_note;
	}
	/**
	 * 属性user_note的Setter方法. 创建日期:
	 * 
	 * @param newUser_note
	 *            java.lang.String
	 */
	public void setUser_note(java.lang.String newUser_note) {
		this.user_note = newUser_note;
	}
	/**
	 * 属性pwdlevelcode的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPwdlevelcode() {
		return pwdlevelcode;
	}
	/**
	 * 属性pwdlevelcode的Setter方法. 创建日期:
	 * 
	 * @param newPwdlevelcode
	 *            java.lang.String
	 */
	public void setPwdlevelcode(java.lang.String newPwdlevelcode) {
		this.pwdlevelcode = newPwdlevelcode;
	}
	/**
	 * 属性pwdparam的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPwdparam() {
		return pwdparam;
	}
	/**
	 * 属性pwdparam的Setter方法. 创建日期:
	 * 
	 * @param newPwdparam
	 *            java.lang.String
	 */
	public void setPwdparam(java.lang.String newPwdparam) {
		this.pwdparam = newPwdparam;
	}
	/**
	 * 属性identityverifycode的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getIdentityverifycode() {
		return identityverifycode;
	}
	/**
	 * 属性identityverifycode的Setter方法. 创建日期:
	 * 
	 * @param newIdentityverifycode
	 *            java.lang.String
	 */
	public void setIdentityverifycode(java.lang.String newIdentityverifycode) {
		this.identityverifycode = newIdentityverifycode;
	}
	/**
	 * 属性abledate的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getAbledate() {
		return abledate;
	}
	/**
	 * 属性abledate的Setter方法. 创建日期:
	 * 
	 * @param newAbledate
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setAbledate(nc.vo.pub.lang.UFDate newAbledate) {
		this.abledate = newAbledate;
	}
	/**
	 * 属性disabledate的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getDisabledate() {
		return disabledate;
	}
	/**
	 * 属性disabledate的Setter方法. 创建日期:
	 * 
	 * @param newDisabledate
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setDisabledate(nc.vo.pub.lang.UFDate newDisabledate) {
		this.disabledate = newDisabledate;
	}
	/**
	 * 属性islocked的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIslocked() {
		return islocked;
	}
	/**
	 * 属性islocked的Setter方法. 创建日期:
	 * 
	 * @param newIslocked
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setIslocked(nc.vo.pub.lang.UFBoolean newIslocked) {
		this.islocked = newIslocked;
	}
	/**
	 * 属性pk_base_doc的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_base_doc() {
		return pk_base_doc;
	}
	/**
	 * 属性pk_base_doc的Setter方法. 创建日期:
	 * 
	 * @param newPk_base_doc
	 *            java.lang.String
	 */
	public void setPk_base_doc(java.lang.String newPk_base_doc) {
		this.pk_base_doc = newPk_base_doc;
	}
	/**
	 * 属性base_doc_type的Getter方法. 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getBase_doc_type() {
		return base_doc_type;
	}
	/**
	 * 属性base_doc_type的Setter方法. 创建日期:
	 * 
	 * @param newBase_doc_type
	 *            java.lang.Integer
	 */
	public void setBase_doc_type(java.lang.Integer newBase_doc_type) {
		this.base_doc_type = newBase_doc_type;
	}
	/**
	 * 属性pk_org的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org() {
		return pk_org;
	}
	/**
	 * 属性pk_org的Setter方法. 创建日期:
	 * 
	 * @param newPk_org
	 *            java.lang.String
	 */
	public void setPk_org(java.lang.String newPk_org) {
		this.pk_org = newPk_org;
	}
	/**
	 * 属性pk_group的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return pk_group;
	}
	/**
	 * 属性pk_group的Setter方法. 创建日期:
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.pk_group = newPk_group;
	}
	/**
	 * 属性creator的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCreator() {
		return creator;
	}
	/**
	 * 属性creator的Setter方法. 创建日期:
	 * 
	 * @param newCreator
	 *            java.lang.String
	 */
	public void setCreator(java.lang.String newCreator) {
		this.creator = newCreator;
	}
	/**
	 * 属性creationtime的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime() {
		return creationtime;
	}
	/**
	 * 属性creationtime的Setter方法. 创建日期:
	 * 
	 * @param newCreationtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
		this.creationtime = newCreationtime;
	}
	/**
	 * 属性modifier的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getModifier() {
		return modifier;
	}
	/**
	 * 属性modifier的Setter方法. 创建日期:
	 * 
	 * @param newModifier
	 *            java.lang.String
	 */
	public void setModifier(java.lang.String newModifier) {
		this.modifier = newModifier;
	}
	/**
	 * 属性modifiedtime的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime() {
		return modifiedtime;
	}
	/**
	 * 属性modifiedtime的Setter方法. 创建日期:
	 * 
	 * @param newModifiedtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
		this.modifiedtime = newModifiedtime;
	}
	/**
	 * 属性user_type的Getter方法. 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getUser_type() {
		return user_type;
	}
	/**
	 * 属性user_type的Setter方法. 创建日期:
	 * 
	 * @param newUser_type
	 *            java.lang.Integer
	 */
	public void setUser_type(java.lang.Integer newUser_type) {
		this.user_type = newUser_type;
	}
	/**
	 * 属性pk_usergroupforcreate的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_usergroupforcreate() {
		return pk_usergroupforcreate;
	}
	/**
	 * 属性pk_usergroupforcreate的Setter方法. 创建日期:
	 * 
	 * @param newPk_usergroupforcreate
	 *            java.lang.String
	 */
	public void setPk_usergroupforcreate(java.lang.String newPk_usergroupforcreate) {
		this.pk_usergroupforcreate = newPk_usergroupforcreate;
	}
	/**
	 * 属性format的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getFormat() {
		return format;
	}
	/**
	 * 属性format的Setter方法. 创建日期:
	 * 
	 * @param newFormat
	 *            java.lang.String
	 */
	public void setFormat(java.lang.String newFormat) {
		this.format = newFormat;
	}
	/**
	 * 属性isca的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsca() {
		return isca;
	}
	/**
	 * 属性isca的Setter方法. 创建日期:
	 * 
	 * @param newIsca
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setIsca(nc.vo.pub.lang.UFBoolean newIsca) {
		this.isca = newIsca;
	}
	/**
	 * 属性enablestate的Getter方法. 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getEnablestate() {
		return enablestate;
	}
	/**
	 * 属性enablestate的Setter方法. 创建日期:
	 * 
	 * @param newEnablestate
	 *            java.lang.Integer
	 */
	public void setEnablestate(java.lang.Integer newEnablestate) {
		this.enablestate = newEnablestate;
	}
	/**
	 * 属性contentlang的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getContentlang() {
		return contentlang;
	}
	/**
	 * 属性contentlang的Setter方法. 创建日期:
	 * 
	 * @param newContentlang
	 *            java.lang.String
	 */
	public void setContentlang(java.lang.String newContentlang) {
		this.contentlang = newContentlang;
	}
	/**
	 * 属性user_code_q的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getUser_code_q() {
		return user_code_q;
	}
	/**
	 * 属性user_code_q的Setter方法. 创建日期:
	 * 
	 * @param newUser_code_q
	 *            java.lang.String
	 */
	public void setUser_code_q(java.lang.String newUser_code_q) {
		this.user_code_q = newUser_code_q;
	}
	/**
	 * 属性dataoriginflag的Getter方法. 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDataoriginflag() {
		return dataoriginflag;
	}
	/**
	 * 属性dataoriginflag的Setter方法. 创建日期:
	 * 
	 * @param newDataoriginflag
	 *            java.lang.Integer
	 */
	public void setDataoriginflag(java.lang.Integer newDataoriginflag) {
		this.dataoriginflag = newDataoriginflag;
	}
	/**
	 * 属性dr的Getter方法. 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}
	/**
	 * 属性dr的Setter方法. 创建日期:
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}
	/**
	 * 属性ts的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}
	/**
	 * 属性ts的Setter方法. 创建日期:
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}
	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}
	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "cuserid";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_user";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_user";
	}
	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:
	 */
	
	
	public CpUserVO() {
		super();
	}
	public UFBoolean getIsasyntonc() {
		return isasyntonc;
	}
	public void setIsasyntonc(UFBoolean isasyntonc) {
		this.isasyntonc = isasyntonc;
	}
}
