/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpUserGroupRoleVO extends SuperVO {
	private java.lang.String pk_usergroup;
	private java.lang.String pk_usergrouprole;
	private java.lang.String pk_role;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_USERGROUP = "pk_usergroup";
	public static final String PK_USERGROUPROLE = "pk_usergrouprole";
	public static final String PK_ROLE = "pk_role";
			
	/**
	 * 属性pk_usergroup的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_usergroup () {
		return pk_usergroup;
	}   
	/**
	 * 属性pk_usergroup的Setter方法.
	 * 创建日期:
	 * @param newPk_usergroup java.lang.String
	 */
	public void setPk_usergroup (java.lang.String newPk_usergroup ) {
	 	this.pk_usergroup = newPk_usergroup;
	} 	  
	/**
	 * 属性pk_usergrouprole的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_usergrouprole () {
		return pk_usergrouprole;
	}   
	/**
	 * 属性pk_usergrouprole的Setter方法.
	 * 创建日期:
	 * @param newPk_usergrouprole java.lang.String
	 */
	public void setPk_usergrouprole (java.lang.String newPk_usergrouprole ) {
	 	this.pk_usergrouprole = newPk_usergrouprole;
	} 	  
	/**
	 * 属性pk_role的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_role () {
		return pk_role;
	}   
	/**
	 * 属性pk_role的Setter方法.
	 * 创建日期:
	 * @param newPk_role java.lang.String
	 */
	public void setPk_role (java.lang.String newPk_role ) {
	 	this.pk_role = newPk_role;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_usergroup";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_usergrouprole";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_usergrouprole";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_usergrouprole";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpUserGroupRoleVO() {
		super();	
	}    
} 


