/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
import nc.vo.pub.SuperVO;
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial") public class CpUserGroupVO extends SuperVO {
	private java.lang.String pk_usergroup;
	private java.lang.String ncpk;
	private java.lang.String original;	
	private java.lang.String group_name;
	private java.lang.String group_code;
	private nc.vo.pub.lang.UFDate createddate;
	private java.lang.String createduser;
	private java.lang.String group_type;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.String pk_parent;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;
	public static final String PK_USERGROUP = "pk_usergroup";
	public static final String GROUP_NAME = "group_name";
	public static final String GROUP_CODE = "group_code";
	public static final String CREATEDDATE = "createddate";
	public static final String CREATEDUSER = "createduser";
	public static final String GROUP_TYPE = "group_type";
	public static final String PK_GROUP = "pk_group";
	/**
	 * 属性pk_usergroup的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_usergroup() {
		return pk_usergroup;
	}
	/**
	 * 属性pk_usergroup的Setter方法. 创建日期:
	 * 
	 * @param newPk_usergroup
	 *            java.lang.String
	 */
	public void setPk_usergroup(java.lang.String newPk_usergroup) {
		this.pk_usergroup = newPk_usergroup;
	}
	
	public java.lang.String getNcpk() {
		return ncpk;
	}
	public void setNcpk(java.lang.String ncpk) {
		this.ncpk = ncpk;
	}
	
	public java.lang.String getOriginal() {
		return original;
	}
	public void setOriginal(java.lang.String original) {
		this.original = original;
	}
	/**
	 * 属性group_name的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getGroup_name() {
		return group_name;
	}
	/**
	 * 属性group_name的Setter方法. 创建日期:
	 * 
	 * @param newGroup_name
	 *            java.lang.String
	 */
	public void setGroup_name(java.lang.String newGroup_name) {
		this.group_name = newGroup_name;
	}
	/**
	 * 属性group_code的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getGroup_code() {
		return group_code;
	}
	/**
	 * 属性group_code的Setter方法. 创建日期:
	 * 
	 * @param newGroup_code
	 *            java.lang.String
	 */
	public void setGroup_code(java.lang.String newGroup_code) {
		this.group_code = newGroup_code;
	}
	/**
	 * 属性createddate的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCreateddate() {
		return createddate;
	}
	/**
	 * 属性createddate的Setter方法. 创建日期:
	 * 
	 * @param newCreateddate
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setCreateddate(nc.vo.pub.lang.UFDate newCreateddate) {
		this.createddate = newCreateddate;
	}
	/**
	 * 属性createduser的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCreateduser() {
		return createduser;
	}
	/**
	 * 属性createduser的Setter方法. 创建日期:
	 * 
	 * @param newCreateduser
	 *            java.lang.String
	 */
	public void setCreateduser(java.lang.String newCreateduser) {
		this.createduser = newCreateduser;
	}
	/**
	 * 属性group_type的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getGroup_type() {
		return group_type;
	}
	/**
	 * 属性group_type的Setter方法. 创建日期:
	 * 
	 * @param newGroup_type
	 *            java.lang.String
	 */
	public void setGroup_type(java.lang.String newGroup_type) {
		this.group_type = newGroup_type;
	}
	
	public java.lang.String getPk_org() {
		return pk_org;
	}
	public void setPk_org(java.lang.String pk_org) {
		this.pk_org = pk_org;
	}
	
	public java.lang.String getPk_group() {
		return pk_group;
	}
	public void setPk_group(java.lang.String pk_group) {
		this.pk_group = pk_group;
	}
	public java.lang.String getPk_parent() {
		return pk_parent;
	}
	public void setPk_parent(java.lang.String pk_parent) {
		this.pk_parent = pk_parent;
	}
	/**
	 * 属性dr的Getter方法. 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}
	/**
	 * 属性dr的Setter方法. 创建日期:
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}
	/**
	 * 属性ts的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}
	/**
	 * 属性ts的Setter方法. 创建日期:
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}
	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}
	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_usergroup";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_usergroup";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_usergroup";
	}
	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:
	 */
	public CpUserGroupVO() {
		super();
	}
}
