/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
import nc.vo.pub.SuperVO;
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial") public class CpUserGroupUserVO extends SuperVO {
	private java.lang.String pk_usergroup;
	private java.lang.String pk_usergroupuser;
	private java.lang.String pk_user;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;
	public static final String PK_USERGROUP = "pk_usergroup";
	public static final String PK_USERGROUPUSER = "pk_usergroupuser";
	public static final String PK_USER = "pk_user";
	/**
	 * 属性pk_usergroup的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_usergroup() {
		return pk_usergroup;
	}
	/**
	 * 属性pk_usergroup的Setter方法. 创建日期:
	 * 
	 * @param newPk_usergroup
	 *            java.lang.String
	 */
	public void setPk_usergroup(java.lang.String newPk_usergroup) {
		this.pk_usergroup = newPk_usergroup;
	}
	/**
	 * 属性pk_usergroupuser的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_usergroupuser() {
		return pk_usergroupuser;
	}
	/**
	 * 属性pk_usergroupuser的Setter方法. 创建日期:
	 * 
	 * @param newPk_usergroupuser
	 *            java.lang.String
	 */
	public void setPk_usergroupuser(java.lang.String newPk_usergroupuser) {
		this.pk_usergroupuser = newPk_usergroupuser;
	}
	/**
	 * 属性pk_user的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_user() {
		return pk_user;
	}
	/**
	 * 属性pk_user的Setter方法. 创建日期:
	 * 
	 * @param newPk_user
	 *            java.lang.String
	 */
	public void setPk_user(java.lang.String newPk_user) {
		this.pk_user = newPk_user;
	}
	/**
	 * 属性dr的Getter方法. 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}
	/**
	 * 属性dr的Setter方法. 创建日期:
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}
	/**
	 * 属性ts的Getter方法. 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}
	/**
	 * 属性ts的Setter方法. 创建日期:
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}
	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_usergroup";
	}
	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_usergroupuser";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_usergroupuser";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_usergroupuser";
	}
	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:
	 */
	public CpUserGroupUserVO() {
		super();
	}
}
