/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.dbl.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class DblFormTemplateVO extends SuperVO {
	private nc.vo.pub.lang.UFBoolean isnotenable;
	private java.lang.String pk_formdefinition;
	private java.lang.String pk_formtemplate;
	private byte[] templatecontent;
	private java.lang.String versionstr;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String ISNOTENABLE = "isnotenable";
	public static final String PK_FORMDEFINITION = "pk_formdefinition";
	public static final String PK_FORMTEMPLATE = "pk_formtemplate";
	public static final String TEMPLATECONTENT = "templatecontent";
	public static final String VERSIONSTR = "versionstr";
			
	/**
	 * 属性isnotenable的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsnotenable () {
		return isnotenable;
	}   
	/**
	 * 属性isnotenable的Setter方法.
	 * 创建日期:
	 * @param newIsnotenable nc.vo.pub.lang.UFBoolean
	 */
	public void setIsnotenable (nc.vo.pub.lang.UFBoolean newIsnotenable ) {
	 	this.isnotenable = newIsnotenable;
	} 	  
	/**
	 * 属性pk_formdefinition的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_formdefinition () {
		return pk_formdefinition;
	}   
	/**
	 * 属性pk_formdefinition的Setter方法.
	 * 创建日期:
	 * @param newPk_formdefinition java.lang.String
	 */
	public void setPk_formdefinition (java.lang.String newPk_formdefinition ) {
	 	this.pk_formdefinition = newPk_formdefinition;
	} 	  
	/**
	 * 属性pk_formtemplate的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_formtemplate () {
		return pk_formtemplate;
	}   
	/**
	 * 属性pk_formtemplate的Setter方法.
	 * 创建日期:
	 * @param newPk_formtemplate java.lang.String
	 */
	public void setPk_formtemplate (java.lang.String newPk_formtemplate ) {
	 	this.pk_formtemplate = newPk_formtemplate;
	} 	  
	/**
	 * 属性templatecontent的Getter方法.
	 * 创建日期:
	 * @return java.lang.Object
	 */
	public byte[] getTemplatecontent () {
		return templatecontent;
	}   
	/**
	 * 属性templatecontent的Setter方法.
	 * 创建日期:
	 * @param newTemplatecontent java.lang.Object
	 */
	public void setTemplatecontent (byte[] newTemplatecontent ) {
	 	this.templatecontent = newTemplatecontent;
	} 	  
	/**
	 * 属性versionstr的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVersionstr () {
		return versionstr;
	}   
	/**
	 * 属性versionstr的Setter方法.
	 * 创建日期:
	 * @param newVersionstr java.lang.String
	 */
	public void setVersionstr (java.lang.String newVersionstr ) {
	 	this.versionstr = newVersionstr;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	public String getTemplateStr() {
		return new String(templatecontent);
	}
	public void setTemplateStr(String str) {
		this.templatecontent = str.getBytes();
	}
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_formtemplate";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "dbl_formtemplate";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "dbl_formtemplate";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public DblFormTemplateVO() {
		super();	
	}    
} 


