/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.dbl.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class DblFormDefinitionVO extends SuperVO {
	private java.lang.String name;
	private java.lang.String orderstr;
	private java.lang.String pk_formcategory;
	private java.lang.String pk_formdefinition;
	private java.lang.String rolenames;
	private java.lang.String rolepks;
	private java.lang.String selfdefclass;
	private java.lang.String tabname;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String NAME = "name";
	public static final String ORDERSTR = "orderstr";
	public static final String PK_FORMCATEGORY = "pk_formcategory";
	public static final String PK_FORMDEFINITION = "pk_formdefinition";
	public static final String ROLENAMES = "rolenames";
	public static final String ROLEPKS = "rolepks";
	public static final String SELFDEFCLASS = "selfdefclass";
	public static final String TABNAME = "tabname";
			
	/**
	 * 属性name的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性orderstr的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOrderstr () {
		return orderstr;
	}   
	/**
	 * 属性orderstr的Setter方法.
	 * 创建日期:
	 * @param newOrderstr java.lang.String
	 */
	public void setOrderstr (java.lang.String newOrderstr ) {
	 	this.orderstr = newOrderstr;
	} 	  
	/**
	 * 属性pk_formcategory的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_formcategory () {
		return pk_formcategory;
	}   
	/**
	 * 属性pk_formcategory的Setter方法.
	 * 创建日期:
	 * @param newPk_formcategory java.lang.String
	 */
	public void setPk_formcategory (java.lang.String newPk_formcategory ) {
	 	this.pk_formcategory = newPk_formcategory;
	} 	  
	/**
	 * 属性pk_formdefinition的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_formdefinition () {
		return pk_formdefinition;
	}   
	/**
	 * 属性pk_formdefinition的Setter方法.
	 * 创建日期:
	 * @param newPk_formdefinition java.lang.String
	 */
	public void setPk_formdefinition (java.lang.String newPk_formdefinition ) {
	 	this.pk_formdefinition = newPk_formdefinition;
	} 	  
	/**
	 * 属性rolenames的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRolenames () {
		return rolenames;
	}   
	/**
	 * 属性rolenames的Setter方法.
	 * 创建日期:
	 * @param newRolenames java.lang.String
	 */
	public void setRolenames (java.lang.String newRolenames ) {
	 	this.rolenames = newRolenames;
	} 	  
	/**
	 * 属性rolepks的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRolepks () {
		return rolepks;
	}   
	/**
	 * 属性rolepks的Setter方法.
	 * 创建日期:
	 * @param newRolepks java.lang.String
	 */
	public void setRolepks (java.lang.String newRolepks ) {
	 	this.rolepks = newRolepks;
	} 	  
	/**
	 * 属性selfdefclass的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSelfdefclass () {
		return selfdefclass;
	}   
	/**
	 * 属性selfdefclass的Setter方法.
	 * 创建日期:
	 * @param newSelfdefclass java.lang.String
	 */
	public void setSelfdefclass (java.lang.String newSelfdefclass ) {
	 	this.selfdefclass = newSelfdefclass;
	} 	  
	/**
	 * 属性tabname的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTabname () {
		return tabname;
	}   
	/**
	 * 属性tabname的Setter方法.
	 * 创建日期:
	 * @param newTabname java.lang.String
	 */
	public void setTabname (java.lang.String newTabname ) {
	 	this.tabname = newTabname;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_formdefinition";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "dbl_formdefinition";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "dbl_formdefinition";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public DblFormDefinitionVO() {
		super();	
	}    
} 


