/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.portal.ctrl.office.data;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class OfficeFileUserVO extends SuperVO {
	private java.lang.String pk_fileuser;
	private java.lang.String usercode;
	private java.lang.String pk_file;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_FILEUSER = "pk_fileuser";
	public static final String USERCODE = "usercode";
	public static final String PK_FILE = "pk_file";
			
	/**
	 * 属性pk_fileuser的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_fileuser () {
		return pk_fileuser;
	}   
	/**
	 * 属性pk_fileuser的Setter方法.
	 * 创建日期:
	 * @param newPk_fileuser java.lang.String
	 */
	public void setPk_fileuser (java.lang.String newPk_fileuser ) {
	 	this.pk_fileuser = newPk_fileuser;
	} 	  
	/**
	 * 属性usercode的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUsercode () {
		return usercode;
	}   
	/**
	 * 属性usercode的Setter方法.
	 * 创建日期:
	 * @param newUsercode java.lang.String
	 */
	public void setUsercode (java.lang.String newUsercode ) {
	 	this.usercode = newUsercode;
	} 	  
	/**
	 * 属性pk_file的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_file () {
		return pk_file;
	}   
	/**
	 * 属性pk_file的Setter方法.
	 * 创建日期:
	 * @param newPk_file java.lang.String
	 */
	public void setPk_file (java.lang.String newPk_file ) {
	 	this.pk_file = newPk_file;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_fileuser";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "uapcp_officefileuser";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "uapcp_officefileuser";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public OfficeFileUserVO() {
		super();	
	}    
} 


