/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.portal.ctrl.office.data.sign;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class AuditlogVO extends SuperVO {
	private java.lang.String pk_auditlog;
	private java.lang.String operby;
	private java.lang.String opercode;
	private java.lang.String opertype;
	private java.lang.String signname;
	private java.lang.String signsn;
	private java.lang.String signuser;
	private java.lang.String clientip;
	private nc.vo.pub.lang.UFDateTime opertime;
	private java.lang.String detail;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_AUDITLOG = "pk_auditlog";
	public static final String OPERBY = "operby";
	public static final String OPERCODE = "opercode";
	public static final String OPERTYPE = "opertype";
	public static final String SIGNNAME = "signname";
	public static final String SIGNSN = "signsn";
	public static final String SIGNUSER = "signuser";
	public static final String CLIENTIP = "clientip";
	public static final String OPERTIME = "opertime";
	public static final String DETAIL = "detail";
			
	/**
	 * 属性pk_auditlog的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_auditlog () {
		return pk_auditlog;
	}   
	/**
	 * 属性pk_auditlog的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_auditlog java.lang.String
	 */
	public void setPk_auditlog (java.lang.String newPk_auditlog ) {
	 	this.pk_auditlog = newPk_auditlog;
	} 	  
	/**
	 * 属性operby的Getter方法.属性名：操作者
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOperby () {
		return operby;
	}   
	/**
	 * 属性operby的Setter方法.属性名：操作者
	 * 创建日期:
	 * @param newOperby java.lang.String
	 */
	public void setOperby (java.lang.String newOperby ) {
	 	this.operby = newOperby;
	} 	  
	/**
	 * 属性opercode的Getter方法.属性名：操作者编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOpercode () {
		return opercode;
	}   
	/**
	 * 属性opercode的Setter方法.属性名：操作者编码
	 * 创建日期:
	 * @param newOpercode java.lang.String
	 */
	public void setOpercode (java.lang.String newOpercode ) {
	 	this.opercode = newOpercode;
	} 	  
	/**
	 * 属性opertype的Getter方法.属性名：操作类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOpertype () {
		return opertype;
	}   
	/**
	 * 属性opertype的Setter方法.属性名：操作类型
	 * 创建日期:
	 * @param newOpertype java.lang.String
	 */
	public void setOpertype (java.lang.String newOpertype ) {
	 	this.opertype = newOpertype;
	} 	  
	/**
	 * 属性signname的Getter方法.属性名：印章名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSignname () {
		return signname;
	}   
	/**
	 * 属性signname的Setter方法.属性名：印章名称
	 * 创建日期:
	 * @param newSignname java.lang.String
	 */
	public void setSignname (java.lang.String newSignname ) {
	 	this.signname = newSignname;
	} 	  
	/**
	 * 属性signsn的Getter方法.属性名：印章序号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSignsn () {
		return signsn;
	}   
	/**
	 * 属性signsn的Setter方法.属性名：印章序号
	 * 创建日期:
	 * @param newSignsn java.lang.String
	 */
	public void setSignsn (java.lang.String newSignsn ) {
	 	this.signsn = newSignsn;
	} 	  
	/**
	 * 属性signuser的Getter方法.属性名：印章用户
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSignuser () {
		return signuser;
	}   
	/**
	 * 属性signuser的Setter方法.属性名：印章用户
	 * 创建日期:
	 * @param newSignuser java.lang.String
	 */
	public void setSignuser (java.lang.String newSignuser ) {
	 	this.signuser = newSignuser;
	} 	  
	/**
	 * 属性clientip的Getter方法.属性名：客户端IP
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getClientip () {
		return clientip;
	}   
	/**
	 * 属性clientip的Setter方法.属性名：客户端IP
	 * 创建日期:
	 * @param newClientip java.lang.String
	 */
	public void setClientip (java.lang.String newClientip ) {
	 	this.clientip = newClientip;
	} 	  
	/**
	 * 属性opertime的Getter方法.属性名：操作时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getOpertime () {
		return opertime;
	}   
	/**
	 * 属性opertime的Setter方法.属性名：操作时间
	 * 创建日期:
	 * @param newOpertime nc.vo.pub.lang.UFDateTime
	 */
	public void setOpertime (nc.vo.pub.lang.UFDateTime newOpertime ) {
	 	this.opertime = newOpertime;
	} 	  
	/**
	 * 属性detail的Getter方法.属性名：详细
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDetail () {
		return detail;
	}   
	/**
	 * 属性detail的Setter方法.属性名：详细
	 * 创建日期:
	 * @param newDetail java.lang.String
	 */
	public void setDetail (java.lang.String newDetail ) {
	 	this.detail = newDetail;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_auditlog";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "uapcp_auditlog";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "uapcp_auditlog";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public AuditlogVO() {
		super();	
	}    
} 


