/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.portal.ctrl.office.data.sign;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ServersignVO extends SuperVO {
	private java.lang.String pk_sign;
	private java.lang.String createby;
	private nc.vo.pub.lang.UFDateTime createtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifertime;
	private java.lang.String name;
	private java.lang.String no;
	private java.lang.String pk_lfwfile;
	private java.lang.String owneruser_pk;
	private java.lang.String owneruser_code;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_SIGN = "pk_sign";
	public static final String CREATEBY = "createby";
	public static final String CREATETIME = "createtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFERTIME = "modifertime";
	public static final String NAME = "name";
	public static final String NO = "no";
	public static final String PK_LFWFILE = "pk_lfwfile";
	public static final String OWNERUSER_PK = "owneruser_pk";
	public static final String OWNERUSER_CODE = "owneruser_code";
			
	/**
	 * 属性pk_sign的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_sign () {
		return pk_sign;
	}   
	/**
	 * 属性pk_sign的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_sign java.lang.String
	 */
	public void setPk_sign (java.lang.String newPk_sign ) {
	 	this.pk_sign = newPk_sign;
	} 	  
	/**
	 * 属性createby的Getter方法.属性名：创建者
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreateby () {
		return createby;
	}   
	/**
	 * 属性createby的Setter方法.属性名：创建者
	 * 创建日期:
	 * @param newCreateby java.lang.String
	 */
	public void setCreateby (java.lang.String newCreateby ) {
	 	this.createby = newCreateby;
	} 	  
	/**
	 * 属性createtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreatetime () {
		return createtime;
	}   
	/**
	 * 属性createtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreatetime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreatetime (nc.vo.pub.lang.UFDateTime newCreatetime ) {
	 	this.createtime = newCreatetime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifertime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifertime () {
		return modifertime;
	}   
	/**
	 * 属性modifertime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifertime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifertime (nc.vo.pub.lang.UFDateTime newModifertime ) {
	 	this.modifertime = newModifertime;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：名称
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性no的Getter方法.属性名：序列号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNo () {
		return no;
	}   
	/**
	 * 属性no的Setter方法.属性名：序列号
	 * 创建日期:
	 * @param newNo java.lang.String
	 */
	public void setNo (java.lang.String newNo ) {
	 	this.no = newNo;
	} 	  
	/**
	 * 属性pk_lfwfile的Getter方法.属性名：文件存储ID
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_lfwfile () {
		return pk_lfwfile;
	}   
	/**
	 * 属性pk_lfwfile的Setter方法.属性名：文件存储ID
	 * 创建日期:
	 * @param newPk_lfwfile java.lang.String
	 */
	public void setPk_lfwfile (java.lang.String newPk_lfwfile ) {
	 	this.pk_lfwfile = newPk_lfwfile;
	} 	  
	/**
	 * 属性owneruser_pk的Getter方法.属性名：所属用户PK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOwneruser_pk () {
		return owneruser_pk;
	}   
	/**
	 * 属性owneruser_pk的Setter方法.属性名：所属用户PK
	 * 创建日期:
	 * @param newOwneruser_pk java.lang.String
	 */
	public void setOwneruser_pk (java.lang.String newOwneruser_pk ) {
	 	this.owneruser_pk = newOwneruser_pk;
	} 	  
	/**
	 * 属性owneruser_code的Getter方法.属性名：所属用户
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOwneruser_code () {
		return owneruser_code;
	}   
	/**
	 * 属性owneruser_code的Setter方法.属性名：所属用户
	 * 创建日期:
	 * @param newOwneruser_code java.lang.String
	 */
	public void setOwneruser_code (java.lang.String newOwneruser_code ) {
	 	this.owneruser_code = newOwneruser_code;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_sign";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "uapcp_serversign";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "uapcp_serversign";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ServersignVO() {
		super();	
	}    
} 


