/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
import nc.vo.pub.SuperVO;
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial") public class WfmBeforeAddSignVO extends SuperVO {
	private java.lang.String pk_beforeaddsign;
	private java.lang.String pk_task;
	private java.lang.String beforeaddsigntime;
	private java.lang.String boforeaddsigntype;
	private java.lang.String scratchpad;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private WfmAddSignUserVO[] addSignUserVos;
	public static final String PK_BEFOREADDSIGN = "pk_beforeaddsign";
	public static final String PK_TASK = "pk_task";
	public static final String BEFOREADDSIGNTIME = "beforeaddsigntime";
	public static final String BOFOREADDSIGNTYPE = "boforeaddsigntype";
	public static final String SCRATCHPAD = "scratchpad";
	/**
	 * 属性pk_beforeaddsign的Getter方法.属性名：前加签主键 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_beforeaddsign() {
		return pk_beforeaddsign;
	}
	/**
	 * 属性pk_beforeaddsign的Setter方法.属性名：前加签主键 创建日期:
	 * 
	 * @param newPk_beforeaddsign
	 *            java.lang.String
	 */
	public void setPk_beforeaddsign(java.lang.String newPk_beforeaddsign) {
		this.pk_beforeaddsign = newPk_beforeaddsign;
	}
	/**
	 * 属性pk_task的Getter方法.属性名：任务主键 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_task() {
		return pk_task;
	}
	/**
	 * 属性pk_task的Setter方法.属性名：任务主键 创建日期:
	 * 
	 * @param newPk_task
	 *            java.lang.String
	 */
	public void setPk_task(java.lang.String newPk_task) {
		this.pk_task = newPk_task;
	}
	/**
	 * 属性beforeaddsigntime的Getter方法.属性名：前加签时间 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBeforeaddsigntime() {
		return beforeaddsigntime;
	}
	/**
	 * 属性beforeaddsigntime的Setter方法.属性名：前加签时间 创建日期:
	 * 
	 * @param newBeforeaddsigntime
	 *            java.lang.String
	 */
	public void setBeforeaddsigntime(java.lang.String newBeforeaddsigntime) {
		this.beforeaddsigntime = newBeforeaddsigntime;
	}
	/**
	 * 属性boforeaddsigntype的Getter方法.属性名：前加签类型 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBoforeaddsigntype() {
		return boforeaddsigntype;
	}
	/**
	 * 属性boforeaddsigntype的Setter方法.属性名：前加签类型 创建日期:
	 * 
	 * @param newBoforeaddsigntype
	 *            java.lang.String
	 */
	public void setBoforeaddsigntype(java.lang.String newBoforeaddsigntype) {
		this.boforeaddsigntype = newBoforeaddsigntype;
	}
	/**
	 * 属性scratchpad的Getter方法.属性名：前加签便签 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getScratchpad() {
		return scratchpad;
	}
	/**
	 * 属性scratchpad的Setter方法.属性名：前加签便签 创建日期:
	 * 
	 * @param newScratchpad
	 *            java.lang.String
	 */
	public void setScratchpad(java.lang.String newScratchpad) {
		this.scratchpad = newScratchpad;
	}
	/**
	 * 属性dr的Getter方法.属性名：dr 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}
	/**
	 * 属性dr的Setter方法.属性名：dr 创建日期:
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}
	/**
	 * 属性ts的Getter方法.属性名：ts 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}
	/**
	 * 属性ts的Setter方法.属性名：ts 创建日期:
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}
	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}
	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_beforeaddsign";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_beforeaddsign";
	}
	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_beforeaddsign";
	}
	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:
	 */
	public WfmBeforeAddSignVO() {
		super();
	}
	public WfmAddSignUserVO[] getAddSignUserVos() {
		return addSignUserVos;
	}
	public void setAddSignUserVos(WfmAddSignUserVO[] addSignUserVos) {
		this.addSignUserVos = addSignUserVos;
	}
}
