/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmCommonWordVO extends SuperVO {
	private java.lang.String contents;
	private java.lang.String pk_commonword;
	private java.lang.String pk_obj;
	private java.lang.String scope;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;
	
	/*范围类型*/
	/**用户范围的*/
	public static final int SCOPE_USER = 0;
	/**角色范围的*/
	public static final int SCOPE_ROLE = 1;
	/**组织范围的*/
	public static final int SCOPE_ORG = 2;
	/**集团范围的*/
	public static final int SCOPE_GROUP = 3;
	/**系统范围*/
	public static final int SCOPE_SYS = 4;
	
	/**常用语范围类型为系统时，对象主键使用的统一值*/
	public static final String OBJ_SYS = "********************";

	public static final String CONTENTS = "contents";
	public static final String PK_COMMONWORD = "pk_commonword";
	public static final String PK_OBJ = "pk_obj";
	public static final String SCOPE = "scope";
			
	/**
	 * 属性contents的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getContents () {
		return contents;
	}   
	/**
	 * 属性contents的Setter方法.
	 * 创建日期:
	 * @param newContents java.lang.String
	 */
	public void setContents (java.lang.String newContents ) {
	 	this.contents = newContents;
	} 	  
	/**
	 * 属性pk_commonword的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_commonword () {
		return pk_commonword;
	}   
	/**
	 * 属性pk_commonword的Setter方法.
	 * 创建日期:
	 * @param newPk_commonword java.lang.String
	 */
	public void setPk_commonword (java.lang.String newPk_commonword ) {
	 	this.pk_commonword = newPk_commonword;
	} 	  
	/**
	 * 属性pk_obj的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_obj () {
		return pk_obj;
	}   
	/**
	 * 属性pk_obj的Setter方法.
	 * 创建日期:
	 * @param newPk_obj java.lang.String
	 */
	public void setPk_obj (java.lang.String newPk_obj ) {
	 	this.pk_obj = newPk_obj;
	} 	  
	/**
	 * 属性scope的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getScope () {
		return scope;
	}   
	/**
	 * 属性scope的Setter方法.
	 * 创建日期:
	 * @param newScope java.lang.String
	 */
	public void setScope (java.lang.String newScope ) {
	 	this.scope = newScope;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_commonword";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_commonword";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_commonword";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmCommonWordVO() {
		super();	
	}    
} 


