/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmFlowPortVO extends SuperVO {
	private java.lang.String pk_flowport;
	private java.lang.String ctrlitem;
	private java.lang.String ctrlstate;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_FLOWPORT = "pk_flowport";
	public static final String CTRLITEM = "ctrlitem";
	public static final String CTRLSTATE = "ctrlstate";
			
	/**
	 * 属性pk_flowport的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_flowport () {
		return pk_flowport;
	}   
	/**
	 * 属性pk_flowport的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_flowport java.lang.String
	 */
	public void setPk_flowport (java.lang.String newPk_flowport ) {
	 	this.pk_flowport = newPk_flowport;
	} 	  
	/**
	 * 属性ctrlitem的Getter方法.属性名：控制项
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCtrlitem () {
		return ctrlitem;
	}   
	/**
	 * 属性ctrlitem的Setter方法.属性名：控制项
	 * 创建日期:
	 * @param newCtrlitem java.lang.String
	 */
	public void setCtrlitem (java.lang.String newCtrlitem ) {
	 	this.ctrlitem = newCtrlitem;
	} 	  
	/**
	 * 属性ctrlstate的Getter方法.属性名：状态值
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCtrlstate () {
		return ctrlstate;
	}   
	/**
	 * 属性ctrlstate的Setter方法.属性名：状态值
	 * 创建日期:
	 * @param newCtrlstate java.lang.String
	 */
	public void setCtrlstate (java.lang.String newCtrlstate ) {
	 	this.ctrlstate = newCtrlstate;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_flowport";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_flowtype";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_flowtype";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmFlowPortVO() {
		super();	
	}    
} 


