/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmFlwTypeVO extends SuperVO {
	private java.lang.String pk_flwtype;
	private java.lang.String typename;
	private java.lang.String typecode;
	private java.lang.String pk_parent;
	private java.lang.String pk_org;
	private java.lang.String pk_flwcat;
	private java.lang.String serverclass;
	private java.lang.String pageid;
	private java.lang.String pk_group;
	private nc.vo.pub.lang.UFBoolean isinner;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_FLWTYPE = "pk_flwtype";
	public static final String TYPENAME = "typename";
	public static final String TYPECODE = "typecode";
	public static final String PK_PARENT = "pk_parent";
	public static final String PK_ORG = "pk_org";
	public static final String PK_FLWCAT = "pk_flwcat";
	public static final String SERVERCLASS = "serverclass";
	public static final String PAGEID = "pageid";
	public static final String PK_GROUP = "pk_group";
	public static final String ISINNER = "isinner";
			
	/**
	 * 属性pk_flwtype的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_flwtype () {
		return pk_flwtype;
	}   
	/**
	 * 属性pk_flwtype的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_flwtype java.lang.String
	 */
	public void setPk_flwtype (java.lang.String newPk_flwtype ) {
	 	this.pk_flwtype = newPk_flwtype;
	} 	  
	/**
	 * 属性typename的Getter方法.属性名：类型名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTypename () {
		return typename;
	}   
	/**
	 * 属性typename的Setter方法.属性名：类型名称
	 * 创建日期:
	 * @param newTypename java.lang.String
	 */
	public void setTypename (java.lang.String newTypename ) {
	 	this.typename = newTypename;
	} 	  
	/**
	 * 属性typecode的Getter方法.属性名：类型编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTypecode () {
		return typecode;
	}   
	/**
	 * 属性typecode的Setter方法.属性名：类型编码
	 * 创建日期:
	 * @param newTypecode java.lang.String
	 */
	public void setTypecode (java.lang.String newTypecode ) {
	 	this.typecode = newTypecode;
	} 	  
	/**
	 * 属性pk_parent的Getter方法.属性名：父类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_parent () {
		return pk_parent;
	}   
	/**
	 * 属性pk_parent的Setter方法.属性名：父类型
	 * 创建日期:
	 * @param newPk_parent java.lang.String
	 */
	public void setPk_parent (java.lang.String newPk_parent ) {
	 	this.pk_parent = newPk_parent;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_flwcat的Getter方法.属性名：所属分类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_flwcat () {
		return pk_flwcat;
	}   
	/**
	 * 属性pk_flwcat的Setter方法.属性名：所属分类
	 * 创建日期:
	 * @param newPk_flwcat java.lang.String
	 */
	public void setPk_flwcat (java.lang.String newPk_flwcat ) {
	 	this.pk_flwcat = newPk_flwcat;
	} 	  
	/**
	 * 属性serverclass的Getter方法.属性名：服务类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getServerclass () {
		return serverclass;
	}   
	/**
	 * 属性serverclass的Setter方法.属性名：服务类
	 * 创建日期:
	 * @param newServerclass java.lang.String
	 */
	public void setServerclass (java.lang.String newServerclass ) {
	 	this.serverclass = newServerclass;
	} 	  
	/**
	 * 属性pageid的Getter方法.属性名：功能节点ID
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPageid () {
		return pageid;
	}   
	/**
	 * 属性pageid的Setter方法.属性名：功能节点ID
	 * 创建日期:
	 * @param newPageid java.lang.String
	 */
	public void setPageid (java.lang.String newPageid ) {
	 	this.pageid = newPageid;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性isinner的Getter方法.属性名：是否是内置
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsinner () {
		return isinner;
	}   
	/**
	 * 属性isinner的Setter方法.属性名：是否是内置
	 * 创建日期:
	 * @param newIsinner nc.vo.pub.lang.UFBoolean
	 */
	public void setIsinner (nc.vo.pub.lang.UFBoolean newIsinner ) {
	 	this.isinner = newIsinner;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_flwtype";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_flwtype";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_flwtype";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmFlwTypeVO() {
		super();	
	}    
} 


