/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmFrmNumElemVO extends SuperVO {
	private java.lang.String pk_frmnumrule;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String filltype;
	private java.lang.String fillvalue;
	private java.lang.String alllength;
	private java.lang.String startvalue;
	private java.lang.String stepvalue;
	private java.lang.String constvalue;
	private java.lang.String datepartten;
	private java.lang.String orderstr;
	private java.lang.String type;
	private java.lang.String pk_frmnumelem;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_FRMNUMRULE = "pk_frmnumrule";
	public static final String CODE = "code";
	public static final String NAME = "name";
	public static final String FILLTYPE = "filltype";
	public static final String FILLVALUE = "fillvalue";
	public static final String ALLLENGTH = "alllength";
	public static final String STARTVALUE = "startvalue";
	public static final String STEPVALUE = "stepvalue";
	public static final String CONSTVALUE = "constvalue";
	public static final String DATEPARTTEN = "datepartten";
	public static final String ORDERSTR = "orderstr";
	public static final String TYPE = "type";
	public static final String PK_FRMNUMELEM = "pk_frmnumelem";
			
	/**
	 * 属性pk_frmnumrule的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_frmnumrule () {
		return pk_frmnumrule;
	}   
	/**
	 * 属性pk_frmnumrule的Setter方法.
	 * 创建日期:
	 * @param newPk_frmnumrule java.lang.String
	 */
	public void setPk_frmnumrule (java.lang.String newPk_frmnumrule ) {
	 	this.pk_frmnumrule = newPk_frmnumrule;
	} 	  
	/**
	 * 属性code的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性name的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性filltype的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFilltype () {
		return filltype;
	}   
	/**
	 * 属性filltype的Setter方法.
	 * 创建日期:
	 * @param newFilltype java.lang.String
	 */
	public void setFilltype (java.lang.String newFilltype ) {
	 	this.filltype = newFilltype;
	} 	  
	/**
	 * 属性fillvalue的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFillvalue () {
		return fillvalue;
	}   
	/**
	 * 属性fillvalue的Setter方法.
	 * 创建日期:
	 * @param newFillvalue java.lang.String
	 */
	public void setFillvalue (java.lang.String newFillvalue ) {
	 	this.fillvalue = newFillvalue;
	} 	  
	/**
	 * 属性alllength的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getAlllength () {
		return alllength;
	}   
	/**
	 * 属性alllength的Setter方法.
	 * 创建日期:
	 * @param newAlllength java.lang.String
	 */
	public void setAlllength (java.lang.String newAlllength ) {
	 	this.alllength = newAlllength;
	} 	  
	/**
	 * 属性startvalue的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getStartvalue () {
		return startvalue;
	}   
	/**
	 * 属性startvalue的Setter方法.
	 * 创建日期:
	 * @param newStartvalue java.lang.String
	 */
	public void setStartvalue (java.lang.String newStartvalue ) {
	 	this.startvalue = newStartvalue;
	} 	  
	/**
	 * 属性stepvalue的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getStepvalue () {
		return stepvalue;
	}   
	/**
	 * 属性stepvalue的Setter方法.
	 * 创建日期:
	 * @param newStepvalue java.lang.String
	 */
	public void setStepvalue (java.lang.String newStepvalue ) {
	 	this.stepvalue = newStepvalue;
	} 	  
	/**
	 * 属性constvalue的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getConstvalue () {
		return constvalue;
	}   
	/**
	 * 属性constvalue的Setter方法.
	 * 创建日期:
	 * @param newConstvalue java.lang.String
	 */
	public void setConstvalue (java.lang.String newConstvalue ) {
	 	this.constvalue = newConstvalue;
	} 	  
	/**
	 * 属性datepartten的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDatepartten () {
		return datepartten;
	}   
	/**
	 * 属性datepartten的Setter方法.
	 * 创建日期:
	 * @param newDatepartten java.lang.String
	 */
	public void setDatepartten (java.lang.String newDatepartten ) {
	 	this.datepartten = newDatepartten;
	} 	  
	/**
	 * 属性orderstr的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOrderstr () {
		return orderstr;
	}   
	/**
	 * 属性orderstr的Setter方法.
	 * 创建日期:
	 * @param newOrderstr java.lang.String
	 */
	public void setOrderstr (java.lang.String newOrderstr ) {
	 	this.orderstr = newOrderstr;
	} 	  
	/**
	 * 属性type的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.
	 * 创建日期:
	 * @param newType java.lang.String
	 */
	public void setType (java.lang.String newType ) {
	 	this.type = newType;
	} 	  
	/**
	 * 属性pk_frmnumelem的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_frmnumelem () {
		return pk_frmnumelem;
	}   
	/**
	 * 属性pk_frmnumelem的Setter方法.
	 * 创建日期:
	 * @param newPk_frmnumelem java.lang.String
	 */
	public void setPk_frmnumelem (java.lang.String newPk_frmnumelem ) {
	 	this.pk_frmnumelem = newPk_frmnumelem;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_frmnumrule";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_frmnumelem";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_frmnumelem";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_frmnumelem";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmFrmNumElemVO() {
		super();	
	}    
} 


