/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmFlowAgentVO extends SuperVO {
	private java.lang.String pk_flowagent;
	private java.lang.String pk_flowtype;
	private java.lang.String pk_user;
	private nc.vo.pub.lang.UFDateTime startdate;
	private nc.vo.pub.lang.UFDateTime stopdate;
	private nc.vo.pub.lang.UFBoolean useflag;
	private java.lang.String pk_agent;
	private java.lang.String pk_agenttype;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_FLOWAGENT = "pk_flowagent";
	public static final String PK_FLOWTYPE = "pk_flowtype";
	public static final String PK_USER = "pk_user";
	public static final String STARTDATE = "startdate";
	public static final String STOPDATE = "stopdate";
	public static final String USEFLAG = "useflag";
	public static final String PK_AGENT = "pk_agent";
	public static final String PK_AGENTTYPE = "pk_agenttype";
			
	/**
	 * 属性pk_flowagent的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_flowagent () {
		return pk_flowagent;
	}   
	/**
	 * 属性pk_flowagent的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_flowagent java.lang.String
	 */
	public void setPk_flowagent (java.lang.String newPk_flowagent ) {
	 	this.pk_flowagent = newPk_flowagent;
	} 	  
	/**
	 * 属性pk_flowtype的Getter方法.属性名：流程类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_flowtype () {
		return pk_flowtype;
	}   
	/**
	 * 属性pk_flowtype的Setter方法.属性名：流程类型
	 * 创建日期:
	 * @param newPk_flowtype java.lang.String
	 */
	public void setPk_flowtype (java.lang.String newPk_flowtype ) {
	 	this.pk_flowtype = newPk_flowtype;
	} 	  
	/**
	 * 属性pk_user的Getter方法.属性名：被代理人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_user () {
		return pk_user;
	}   
	/**
	 * 属性pk_user的Setter方法.属性名：被代理人
	 * 创建日期:
	 * @param newPk_user java.lang.String
	 */
	public void setPk_user (java.lang.String newPk_user ) {
	 	this.pk_user = newPk_user;
	} 	  
	/**
	 * 属性startdate的Getter方法.属性名：开始时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getStartdate () {
		return startdate;
	}   
	/**
	 * 属性startdate的Setter方法.属性名：开始时间
	 * 创建日期:
	 * @param newStartdate nc.vo.pub.lang.UFDateTime
	 */
	public void setStartdate (nc.vo.pub.lang.UFDateTime newStartdate ) {
	 	this.startdate = newStartdate;
	} 	  
	/**
	 * 属性stopdate的Getter方法.属性名：结束时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getStopdate () {
		return stopdate;
	}   
	/**
	 * 属性stopdate的Setter方法.属性名：结束时间
	 * 创建日期:
	 * @param newStopdate nc.vo.pub.lang.UFDateTime
	 */
	public void setStopdate (nc.vo.pub.lang.UFDateTime newStopdate ) {
	 	this.stopdate = newStopdate;
	} 	  
	/**
	 * 属性useflag的Getter方法.属性名：是否启用
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getUseflag () {
		return useflag;
	}   
	/**
	 * 属性useflag的Setter方法.属性名：是否启用
	 * 创建日期:
	 * @param newUseflag nc.vo.pub.lang.UFBoolean
	 */
	public void setUseflag (nc.vo.pub.lang.UFBoolean newUseflag ) {
	 	this.useflag = newUseflag;
	} 	  
	/**
	 * 属性pk_agent的Getter方法.属性名：代理人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_agent () {
		return pk_agent;
	}   
	/**
	 * 属性pk_agent的Setter方法.属性名：代理人
	 * 创建日期:
	 * @param newPk_agent java.lang.String
	 */
	public void setPk_agent (java.lang.String newPk_agent ) {
	 	this.pk_agent = newPk_agent;
	} 	  
	/**
	 * 属性pk_agenttype的Getter方法.属性名：代理类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_agenttype () {
		return pk_agenttype;
	}   
	/**
	 * 属性pk_agenttype的Setter方法.属性名：代理类型
	 * 创建日期:
	 * @param newPk_agenttype java.lang.String
	 */
	public void setPk_agenttype (java.lang.String newPk_agenttype ) {
	 	this.pk_agenttype = newPk_agenttype;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_flowagent";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_flowagent";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_flowagent";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmFlowAgentVO() {
		super();	
	}    
} 


