/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmFlwPrtVO extends SuperVO {
	private nc.vo.pub.lang.UFBoolean isnotdispattach;
	private nc.vo.pub.lang.UFBoolean isnotdisphistory;
	private nc.vo.pub.lang.UFBoolean isnotdispimage;
	private nc.vo.pub.lang.UFBoolean isnotdispsubfrm;
	private nc.vo.pub.lang.UFBoolean isnotdispword;
	private java.lang.String pk_flwprt;
	private java.lang.String pk_prodef;
	private java.lang.String port_id;
	private java.lang.String prodef_id;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String ISNOTDISPATTACH = "isnotdispattach";
	public static final String ISNOTDISPHISTORY = "isnotdisphistory";
	public static final String ISNOTDISPIMAGE = "isnotdispimage";
	public static final String ISNOTDISPSUBFRM = "isnotdispsubfrm";
	public static final String ISNOTDISPWORD = "isnotdispword";
	public static final String PK_FLWPRT = "pk_flwprt";
	public static final String PK_PRODEF = "pk_prodef";
	public static final String PORT_ID = "port_id";
	public static final String PRODEF_ID = "prodef_id";
			
	/**
	 * 属性isnotdispattach的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsnotdispattach () {
		return isnotdispattach;
	}   
	/**
	 * 属性isnotdispattach的Setter方法.
	 * 创建日期:
	 * @param newIsnotdispattach nc.vo.pub.lang.UFBoolean
	 */
	public void setIsnotdispattach (nc.vo.pub.lang.UFBoolean newIsnotdispattach ) {
	 	this.isnotdispattach = newIsnotdispattach;
	} 	  
	/**
	 * 属性isnotdisphistory的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsnotdisphistory () {
		return isnotdisphistory;
	}   
	/**
	 * 属性isnotdisphistory的Setter方法.
	 * 创建日期:
	 * @param newIsnotdisphistory nc.vo.pub.lang.UFBoolean
	 */
	public void setIsnotdisphistory (nc.vo.pub.lang.UFBoolean newIsnotdisphistory ) {
	 	this.isnotdisphistory = newIsnotdisphistory;
	} 	  
	/**
	 * 属性isnotdispimage的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsnotdispimage () {
		return isnotdispimage;
	}   
	/**
	 * 属性isnotdispimage的Setter方法.
	 * 创建日期:
	 * @param newIsnotdispimage nc.vo.pub.lang.UFBoolean
	 */
	public void setIsnotdispimage (nc.vo.pub.lang.UFBoolean newIsnotdispimage ) {
	 	this.isnotdispimage = newIsnotdispimage;
	} 	  
	/**
	 * 属性isnotdispsubfrm的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsnotdispsubfrm () {
		return isnotdispsubfrm;
	}   
	/**
	 * 属性isnotdispsubfrm的Setter方法.
	 * 创建日期:
	 * @param newIsnotdispsubfrm nc.vo.pub.lang.UFBoolean
	 */
	public void setIsnotdispsubfrm (nc.vo.pub.lang.UFBoolean newIsnotdispsubfrm ) {
	 	this.isnotdispsubfrm = newIsnotdispsubfrm;
	} 	  
	/**
	 * 属性isnotdispword的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsnotdispword () {
		return isnotdispword;
	}   
	/**
	 * 属性isnotdispword的Setter方法.
	 * 创建日期:
	 * @param newIsnotdispword nc.vo.pub.lang.UFBoolean
	 */
	public void setIsnotdispword (nc.vo.pub.lang.UFBoolean newIsnotdispword ) {
	 	this.isnotdispword = newIsnotdispword;
	} 	  
	/**
	 * 属性pk_flwprt的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_flwprt () {
		return pk_flwprt;
	}   
	/**
	 * 属性pk_flwprt的Setter方法.
	 * 创建日期:
	 * @param newPk_flwprt java.lang.String
	 */
	public void setPk_flwprt (java.lang.String newPk_flwprt ) {
	 	this.pk_flwprt = newPk_flwprt;
	} 	  
	/**
	 * 属性pk_prodef的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_prodef () {
		return pk_prodef;
	}   
	/**
	 * 属性pk_prodef的Setter方法.
	 * 创建日期:
	 * @param newPk_prodef java.lang.String
	 */
	public void setPk_prodef (java.lang.String newPk_prodef ) {
	 	this.pk_prodef = newPk_prodef;
	} 	  
	/**
	 * 属性port_id的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPort_id () {
		return port_id;
	}   
	/**
	 * 属性port_id的Setter方法.
	 * 创建日期:
	 * @param newPort_id java.lang.String
	 */
	public void setPort_id (java.lang.String newPort_id ) {
	 	this.port_id = newPort_id;
	} 	  
	/**
	 * 属性prodef_id的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getProdef_id () {
		return prodef_id;
	}   
	/**
	 * 属性prodef_id的Setter方法.
	 * 创建日期:
	 * @param newProdef_id java.lang.String
	 */
	public void setProdef_id (java.lang.String newProdef_id ) {
	 	this.prodef_id = newProdef_id;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_flwprt";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_flwprt";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_flwprt";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmFlwPrtVO() {
		super();	
	}    
} 


