/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmFrmNumRuleVO extends SuperVO {
	private java.lang.String code;
	private java.lang.String codetype;
	private nc.vo.pub.lang.UFBoolean isedit;
	private nc.vo.pub.lang.UFBoolean isfill;
	private java.lang.String name;
	private java.lang.String pk_frmnumrule;
	private java.lang.String pk_flowtype;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String CODE = "code";
	public static final String CODETYPE = "codetype";
	public static final String ISEDIT = "isedit";
	public static final String ISFILL = "isfill";
	public static final String NAME = "name";
	public static final String PK_FRMNUMRULE = "pk_frmnumrule";
	public static final String PK_FLOWTYPE = "pk_flowtype";
			
	/**
	 * 属性code的Getter方法.属性名：编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.属性名：编码
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性codetype的Getter方法.属性名：类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCodetype () {
		return codetype;
	}   
	/**
	 * 属性codetype的Setter方法.属性名：类型
	 * 创建日期:
	 * @param newCodetype java.lang.String
	 */
	public void setCodetype (java.lang.String newCodetype ) {
	 	this.codetype = newCodetype;
	} 	  
	/**
	 * 属性isedit的Getter方法.属性名：是否可编辑
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsedit () {
		return isedit;
	}   
	/**
	 * 属性isedit的Setter方法.属性名：是否可编辑
	 * 创建日期:
	 * @param newIsedit nc.vo.pub.lang.UFBoolean
	 */
	public void setIsedit (nc.vo.pub.lang.UFBoolean newIsedit ) {
	 	this.isedit = newIsedit;
	} 	  
	/**
	 * 属性isfill的Getter方法.属性名：是否断码补码
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsfill () {
		return isfill;
	}   
	/**
	 * 属性isfill的Setter方法.属性名：是否断码补码
	 * 创建日期:
	 * @param newIsfill nc.vo.pub.lang.UFBoolean
	 */
	public void setIsfill (nc.vo.pub.lang.UFBoolean newIsfill ) {
	 	this.isfill = newIsfill;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：名称
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性pk_frmnumrule的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_frmnumrule () {
		return pk_frmnumrule;
	}   
	/**
	 * 属性pk_frmnumrule的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_frmnumrule java.lang.String
	 */
	public void setPk_frmnumrule (java.lang.String newPk_frmnumrule ) {
	 	this.pk_frmnumrule = newPk_frmnumrule;
	} 	  
	/**
	 * 属性pk_flowtype的Getter方法.属性名：业务类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_flowtype () {
		return pk_flowtype;
	}   
	/**
	 * 属性pk_flowtype的Setter方法.属性名：业务类型
	 * 创建日期:
	 * @param newPk_flowtype java.lang.String
	 */
	public void setPk_flowtype (java.lang.String newPk_flowtype ) {
	 	this.pk_flowtype = newPk_flowtype;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_frmnumrule";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_frmnumrule";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_frmnumrule";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmFrmNumRuleVO() {
		super();	
	}    
} 


