/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmQueryconditionVO extends SuperVO {
	private java.lang.String pk_querytemplate;
	private java.lang.String code;
	private java.lang.String defautvalue;
	private nc.vo.pub.lang.UFBoolean isconst;
	private nc.vo.pub.lang.UFBoolean iseditable;
	private nc.vo.pub.lang.UFBoolean isvisible;
	private java.lang.String name;
	private java.lang.String operator;
	private java.lang.String options;
	private java.lang.String pk_querycondition;
	private java.lang.String type;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_QUERYTEMPLATE = "pk_querytemplate";
	public static final String CODE = "code";
	public static final String DEFAUTVALUE = "defautvalue";
	public static final String ISCONST = "isconst";
	public static final String ISEDITABLE = "iseditable";
	public static final String ISVISIBLE = "isvisible";
	public static final String NAME = "name";
	public static final String OPERATOR = "operator";
	public static final String OPTIONS = "options";
	public static final String PK_QUERYCONDITION = "pk_querycondition";
	public static final String TYPE = "type";
			
	/**
	 * 属性pk_querytemplate的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_querytemplate () {
		return pk_querytemplate;
	}   
	/**
	 * 属性pk_querytemplate的Setter方法.
	 * 创建日期:
	 * @param newPk_querytemplate java.lang.String
	 */
	public void setPk_querytemplate (java.lang.String newPk_querytemplate ) {
	 	this.pk_querytemplate = newPk_querytemplate;
	} 	  
	/**
	 * 属性code的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性defautvalue的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDefautvalue () {
		return defautvalue;
	}   
	/**
	 * 属性defautvalue的Setter方法.
	 * 创建日期:
	 * @param newDefautvalue java.lang.String
	 */
	public void setDefautvalue (java.lang.String newDefautvalue ) {
	 	this.defautvalue = newDefautvalue;
	} 	  
	/**
	 * 属性isconst的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsconst () {
		return isconst;
	}   
	/**
	 * 属性isconst的Setter方法.
	 * 创建日期:
	 * @param newIsconst nc.vo.pub.lang.UFBoolean
	 */
	public void setIsconst (nc.vo.pub.lang.UFBoolean newIsconst ) {
	 	this.isconst = newIsconst;
	} 	  
	/**
	 * 属性iseditable的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIseditable () {
		return iseditable;
	}   
	/**
	 * 属性iseditable的Setter方法.
	 * 创建日期:
	 * @param newIseditable nc.vo.pub.lang.UFBoolean
	 */
	public void setIseditable (nc.vo.pub.lang.UFBoolean newIseditable ) {
	 	this.iseditable = newIseditable;
	} 	  
	/**
	 * 属性isvisible的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsvisible () {
		return isvisible;
	}   
	/**
	 * 属性isvisible的Setter方法.
	 * 创建日期:
	 * @param newIsvisible nc.vo.pub.lang.UFBoolean
	 */
	public void setIsvisible (nc.vo.pub.lang.UFBoolean newIsvisible ) {
	 	this.isvisible = newIsvisible;
	} 	  
	/**
	 * 属性name的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性operator的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOperator () {
		return operator;
	}   
	/**
	 * 属性operator的Setter方法.
	 * 创建日期:
	 * @param newOperator java.lang.String
	 */
	public void setOperator (java.lang.String newOperator ) {
	 	this.operator = newOperator;
	} 	  
	/**
	 * 属性options的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOptions () {
		return options;
	}   
	/**
	 * 属性options的Setter方法.
	 * 创建日期:
	 * @param newOptions java.lang.String
	 */
	public void setOptions (java.lang.String newOptions ) {
	 	this.options = newOptions;
	} 	  
	/**
	 * 属性pk_querycondition的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_querycondition () {
		return pk_querycondition;
	}   
	/**
	 * 属性pk_querycondition的Setter方法.
	 * 创建日期:
	 * @param newPk_querycondition java.lang.String
	 */
	public void setPk_querycondition (java.lang.String newPk_querycondition ) {
	 	this.pk_querycondition = newPk_querycondition;
	} 	  
	/**
	 * 属性type的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.
	 * 创建日期:
	 * @param newType java.lang.String
	 */
	public void setType (java.lang.String newType ) {
	 	this.type = newType;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_querytemplate";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_querycondition";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_querycondition";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_querycondition";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmQueryconditionVO() {
		super();	
	}    
} 


