/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmQuerytemplateVO extends SuperVO {
	private java.lang.String ext0;
	private java.lang.String ext1;
	private java.lang.String listener;
	private java.lang.String pagemodel;
	private java.lang.String pk_formdefinition;
	private java.lang.String pk_querytemplate;
	private java.lang.String refclass;
	private java.lang.String templatedesc;
	private java.lang.String templatename;
	private java.lang.String templatetype;
	private java.lang.String url;
	private java.lang.String pk_queryclass;
	private java.lang.Integer dr ;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String EXT0 = "ext0";
	public static final String EXT1 = "ext1";
	public static final String LISTENER = "listener";
	public static final String PAGEMODEL = "pagemodel";
	public static final String PK_FORMDEFINITION = "pk_formdefinition";
	public static final String PK_QUERYTEMPLATE = "pk_querytemplate";
	public static final String REFCLASS = "refclass";
	public static final String TEMPLATEDESC = "templatedesc";
	public static final String TEMPLATENAME = "templatename";
	public static final String TEMPLATETYPE = "templatetype";
	public static final String URL = "url";
	public static final String PK_QUERYCLASS = "pk_queryclass";
			
	/**
	 * 属性ext0的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExt0 () {
		return ext0;
	}   
	/**
	 * 属性ext0的Setter方法.
	 * 创建日期:
	 * @param newExt0 java.lang.String
	 */
	public void setExt0 (java.lang.String newExt0 ) {
	 	this.ext0 = newExt0;
	} 	  
	/**
	 * 属性ext1的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExt1 () {
		return ext1;
	}   
	/**
	 * 属性ext1的Setter方法.
	 * 创建日期:
	 * @param newExt1 java.lang.String
	 */
	public void setExt1 (java.lang.String newExt1 ) {
	 	this.ext1 = newExt1;
	} 	  
	/**
	 * 属性listener的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getListener () {
		return listener;
	}   
	/**
	 * 属性listener的Setter方法.
	 * 创建日期:
	 * @param newListener java.lang.String
	 */
	public void setListener (java.lang.String newListener ) {
	 	this.listener = newListener;
	} 	  
	/**
	 * 属性pagemodel的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPagemodel () {
		return pagemodel;
	}   
	/**
	 * 属性pagemodel的Setter方法.
	 * 创建日期:
	 * @param newPagemodel java.lang.String
	 */
	public void setPagemodel (java.lang.String newPagemodel ) {
	 	this.pagemodel = newPagemodel;
	} 	  
	/**
	 * 属性pk_formdefinition的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_formdefinition () {
		return pk_formdefinition;
	}   
	/**
	 * 属性pk_formdefinition的Setter方法.
	 * 创建日期:
	 * @param newPk_formdefinition java.lang.String
	 */
	public void setPk_formdefinition (java.lang.String newPk_formdefinition ) {
	 	this.pk_formdefinition = newPk_formdefinition;
	} 	  
	/**
	 * 属性pk_querytemplate的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_querytemplate () {
		return pk_querytemplate;
	}   
	/**
	 * 属性pk_querytemplate的Setter方法.
	 * 创建日期:
	 * @param newPk_querytemplate java.lang.String
	 */
	public void setPk_querytemplate (java.lang.String newPk_querytemplate ) {
	 	this.pk_querytemplate = newPk_querytemplate;
	} 	  
	/**
	 * 属性refclass的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRefclass () {
		return refclass;
	}   
	/**
	 * 属性refclass的Setter方法.
	 * 创建日期:
	 * @param newRefclass java.lang.String
	 */
	public void setRefclass (java.lang.String newRefclass ) {
	 	this.refclass = newRefclass;
	} 	  
	/**
	 * 属性templatedesc的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTemplatedesc () {
		return templatedesc;
	}   
	/**
	 * 属性templatedesc的Setter方法.
	 * 创建日期:
	 * @param newTemplatedesc java.lang.String
	 */
	public void setTemplatedesc (java.lang.String newTemplatedesc ) {
	 	this.templatedesc = newTemplatedesc;
	} 	  
	/**
	 * 属性templatename的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTemplatename () {
		return templatename;
	}   
	/**
	 * 属性templatename的Setter方法.
	 * 创建日期:
	 * @param newTemplatename java.lang.String
	 */
	public void setTemplatename (java.lang.String newTemplatename ) {
	 	this.templatename = newTemplatename;
	} 	  
	/**
	 * 属性templatetype的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTemplatetype () {
		return templatetype;
	}   
	/**
	 * 属性templatetype的Setter方法.
	 * 创建日期:
	 * @param newTemplatetype java.lang.String
	 */
	public void setTemplatetype (java.lang.String newTemplatetype ) {
	 	this.templatetype = newTemplatetype;
	} 	  
	/**
	 * 属性url的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUrl () {
		return url;
	}   
	/**
	 * 属性url的Setter方法.
	 * 创建日期:
	 * @param newUrl java.lang.String
	 */
	public void setUrl (java.lang.String newUrl ) {
	 	this.url = newUrl;
	} 	  
	/**
	 * 属性pk_queryclass的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_queryclass () {
		return pk_queryclass;
	}   
	/**
	 * 属性pk_queryclass的Setter方法.
	 * 创建日期:
	 * @param newPk_queryclass java.lang.String
	 */
	public void setPk_queryclass (java.lang.String newPk_queryclass ) {
	 	this.pk_queryclass = newPk_queryclass;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_querytemplate";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_querytemplate";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_querytemplate";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmQuerytemplateVO() {
		super();	
	}    
} 


