/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmQueryclassVO extends SuperVO {
	private java.lang.String ext0;
	private java.lang.String ext1;
	private java.lang.String pk_group;
	private java.lang.String pk_queryclass;
	private java.lang.String queryclasscode;
	private java.lang.String queryclassname;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String EXT0 = "ext0";
	public static final String EXT1 = "ext1";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_QUERYCLASS = "pk_queryclass";
	public static final String QUERYCLASSCODE = "queryclasscode";
	public static final String QUERYCLASSNAME = "queryclassname";
			
	/**
	 * 属性ext0的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExt0 () {
		return ext0;
	}   
	/**
	 * 属性ext0的Setter方法.
	 * 创建日期:
	 * @param newExt0 java.lang.String
	 */
	public void setExt0 (java.lang.String newExt0 ) {
	 	this.ext0 = newExt0;
	} 	  
	/**
	 * 属性ext1的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExt1 () {
		return ext1;
	}   
	/**
	 * 属性ext1的Setter方法.
	 * 创建日期:
	 * @param newExt1 java.lang.String
	 */
	public void setExt1 (java.lang.String newExt1 ) {
	 	this.ext1 = newExt1;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_queryclass的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_queryclass () {
		return pk_queryclass;
	}   
	/**
	 * 属性pk_queryclass的Setter方法.
	 * 创建日期:
	 * @param newPk_queryclass java.lang.String
	 */
	public void setPk_queryclass (java.lang.String newPk_queryclass ) {
	 	this.pk_queryclass = newPk_queryclass;
	} 	  
	/**
	 * 属性queryclasscode的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQueryclasscode () {
		return queryclasscode;
	}   
	/**
	 * 属性queryclasscode的Setter方法.
	 * 创建日期:
	 * @param newQueryclasscode java.lang.String
	 */
	public void setQueryclasscode (java.lang.String newQueryclasscode ) {
	 	this.queryclasscode = newQueryclasscode;
	} 	  
	/**
	 * 属性queryclassname的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQueryclassname () {
		return queryclassname;
	}   
	/**
	 * 属性queryclassname的Setter方法.
	 * 创建日期:
	 * @param newQueryclassname java.lang.String
	 */
	public void setQueryclassname (java.lang.String newQueryclassname ) {
	 	this.queryclassname = newQueryclassname;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_queryclass";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_queryclass";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_queryclass";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmQueryclassVO() {
		super();	
	}    
} 


