/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmSuitPrintVO extends SuperVO {
	private java.lang.String code;
	private byte[] contents;
	private java.lang.String name;
	private java.lang.String orderstr;
	private java.lang.String pk_formdefinition;
	private java.lang.String pk_suitprint;
	private java.lang.String serverclass;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String CODE = "code";
	public static final String CONTENTS = "contents";
	public static final String NAME = "name";
	public static final String ORDERSTR = "orderstr";
	public static final String PK_FORMDEFINITION = "pk_formdefinition";
	public static final String PK_SUITPRINT = "pk_suitprint";
	public static final String SERVERCLASS = "serverclass";
			
	/**
	 * 属性code的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性contents的Getter方法.
	 * 创建日期:
	 * @return java.lang.Object
	 */
	public byte[] getContents () {
		return contents;
	}   
	/**
	 * 属性contents的Setter方法.
	 * 创建日期:
	 * @param newContents java.lang.Object
	 */
	public void setContents (byte[] newContents ) {
	 	this.contents = newContents;
	} 	  
	/**
	 * 属性name的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性orderstr的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOrderstr () {
		return orderstr;
	}   
	/**
	 * 属性orderstr的Setter方法.
	 * 创建日期:
	 * @param newOrderstr java.lang.String
	 */
	public void setOrderstr (java.lang.String newOrderstr ) {
	 	this.orderstr = newOrderstr;
	} 	  
	/**
	 * 属性pk_formdefinition的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_formdefinition () {
		return pk_formdefinition;
	}   
	/**
	 * 属性pk_formdefinition的Setter方法.
	 * 创建日期:
	 * @param newPk_formdefinition java.lang.String
	 */
	public void setPk_formdefinition (java.lang.String newPk_formdefinition ) {
	 	this.pk_formdefinition = newPk_formdefinition;
	} 	  
	/**
	 * 属性pk_suitprint的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_suitprint () {
		return pk_suitprint;
	}   
	/**
	 * 属性pk_suitprint的Setter方法.
	 * 创建日期:
	 * @param newPk_suitprint java.lang.String
	 */
	public void setPk_suitprint (java.lang.String newPk_suitprint ) {
	 	this.pk_suitprint = newPk_suitprint;
	} 	  
	/**
	 * 属性serverclass的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getServerclass () {
		return serverclass;
	}   
	/**
	 * 属性serverclass的Setter方法.
	 * 创建日期:
	 * @param newServerclass java.lang.String
	 */
	public void setServerclass (java.lang.String newServerclass ) {
	 	this.serverclass = newServerclass;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_suitprint";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_suitprint";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_suitprint";
	}    
	public String getSuitprinttmp() {
		return new String(getContents());
	}
	public void setSuitprinttmp(String suitPrintTmp) {
		setContents(suitPrintTmp.getBytes());
	}
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmSuitPrintVO() {
		super();	
	}    
} 


