/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmTaskTabColVO extends SuperVO {
	private java.lang.String dispname;
	private java.lang.String orderstr;
	private java.lang.String pk_prodef;
	private java.lang.String pk_tasktabcol;
	private java.lang.String prodef_id;
	private java.lang.String tabctrlvalue;
	private java.lang.String tabfield_id;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String DISPNAME = "dispname";
	public static final String ORDERSTR = "orderstr";
	public static final String PK_PRODEF = "pk_prodef";
	public static final String PK_TASKTABCOL = "pk_tasktabcol";
	public static final String PRODEF_ID = "prodef_id";
	public static final String TABCTRLVALUE = "tabctrlvalue";
	public static final String TABFIELD_ID = "tabfield_id";
			
	/**
	 * 属性dispname的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDispname () {
		return dispname;
	}   
	/**
	 * 属性dispname的Setter方法.
	 * 创建日期:
	 * @param newDispname java.lang.String
	 */
	public void setDispname (java.lang.String newDispname ) {
	 	this.dispname = newDispname;
	} 	  
	/**
	 * 属性orderstr的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOrderstr () {
		return orderstr;
	}   
	/**
	 * 属性orderstr的Setter方法.
	 * 创建日期:
	 * @param newOrderstr java.lang.String
	 */
	public void setOrderstr (java.lang.String newOrderstr ) {
	 	this.orderstr = newOrderstr;
	} 	  
	/**
	 * 属性pk_prodef的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_prodef () {
		return pk_prodef;
	}   
	/**
	 * 属性pk_prodef的Setter方法.
	 * 创建日期:
	 * @param newPk_prodef java.lang.String
	 */
	public void setPk_prodef (java.lang.String newPk_prodef ) {
	 	this.pk_prodef = newPk_prodef;
	} 	  
	/**
	 * 属性pk_tasktabcol的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_tasktabcol () {
		return pk_tasktabcol;
	}   
	/**
	 * 属性pk_tasktabcol的Setter方法.
	 * 创建日期:
	 * @param newPk_tasktabcol java.lang.String
	 */
	public void setPk_tasktabcol (java.lang.String newPk_tasktabcol ) {
	 	this.pk_tasktabcol = newPk_tasktabcol;
	} 	  
	/**
	 * 属性prodef_id的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getProdef_id () {
		return prodef_id;
	}   
	/**
	 * 属性prodef_id的Setter方法.
	 * 创建日期:
	 * @param newProdef_id java.lang.String
	 */
	public void setProdef_id (java.lang.String newProdef_id ) {
	 	this.prodef_id = newProdef_id;
	} 	  
	/**
	 * 属性tabctrlvalue的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTabctrlvalue () {
		return tabctrlvalue;
	}   
	/**
	 * 属性tabctrlvalue的Setter方法.
	 * 创建日期:
	 * @param newTabctrlvalue java.lang.String
	 */
	public void setTabctrlvalue (java.lang.String newTabctrlvalue ) {
	 	this.tabctrlvalue = newTabctrlvalue;
	} 	  
	/**
	 * 属性tabfield_id的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTabfield_id () {
		return tabfield_id;
	}   
	/**
	 * 属性tabfield_id的Setter方法.
	 * 创建日期:
	 * @param newTabfield_id java.lang.String
	 */
	public void setTabfield_id (java.lang.String newTabfield_id ) {
	 	this.tabfield_id = newTabfield_id;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_tasktabcol";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_tasktabcol";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_tasktabcol";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmTaskTabColVO() {
		super();	
	}    
} 


