/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmVacationVO extends SuperVO {
	private nc.vo.pub.lang.UFDate endday;
	private java.lang.String pk_vacation;
	private java.lang.String remark;
	private nc.vo.pub.lang.UFDate startday;
	private java.lang.String title;
	private java.lang.Integer type;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String ENDDAY = "endday";
	public static final String PK_VACATION = "pk_vacation";
	public static final String REMARK = "remark";
	public static final String STARTDAY = "startday";
	public static final String TITLE = "title";
	public static final String TYPE = "type";
	
	/**
	 * 周末
	 */
	public static final String WEEKEND = "nc.portal.weekend";
	/**
	 * 特殊工作日
	 */
	public static final String SPECIALWORKDAY = "nc.portal.SpecialWorkDay";
	/**
	 * 假期
	 */
	public static final String HOLIDAYS = "nc.portal.Holidays";
			
	/**
	 * 属性endday的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getEndday () {
		return endday;
	}   
	/**
	 * 属性endday的Setter方法.
	 * 创建日期:
	 * @param newEndday nc.vo.pub.lang.UFDate
	 */
	public void setEndday (nc.vo.pub.lang.UFDate newEndday ) {
	 	this.endday = newEndday;
	} 	  
	/**
	 * 属性pk_vacation的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_vacation () {
		return pk_vacation;
	}   
	/**
	 * 属性pk_vacation的Setter方法.
	 * 创建日期:
	 * @param newPk_vacation java.lang.String
	 */
	public void setPk_vacation (java.lang.String newPk_vacation ) {
	 	this.pk_vacation = newPk_vacation;
	} 	  
	/**
	 * 属性remark的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.
	 * 创建日期:
	 * @param newRemark java.lang.String
	 */
	public void setRemark (java.lang.String newRemark ) {
	 	this.remark = newRemark;
	} 	  
	/**
	 * 属性startday的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getStartday () {
		return startday;
	}   
	/**
	 * 属性startday的Setter方法.
	 * 创建日期:
	 * @param newStartday nc.vo.pub.lang.UFDate
	 */
	public void setStartday (nc.vo.pub.lang.UFDate newStartday ) {
	 	this.startday = newStartday;
	} 	  
	/**
	 * 属性title的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle () {
		return title;
	}   
	/**
	 * 属性title的Setter方法.
	 * 创建日期:
	 * @param newTitle java.lang.String
	 */
	public void setTitle (java.lang.String newTitle ) {
	 	this.title = newTitle;
	} 	  
	/**
	 * 属性type的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.
	 * 创建日期:
	 * @param newType java.lang.Integer
	 */
	public void setType (java.lang.Integer newType ) {
	 	this.type = newType;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_vacation";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_vacation";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_vacation";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmVacationVO() {
		super();	
	}    
} 


